### PR TITLE
Pr v1alpha2 ugprade cluster api dependency

### PR DESCRIPTION
**Pull request by sbueringer**
A small PR before switching to kubeadm bootstrapper to use a newer version of ClusterAPI

### CODE REVIEW

**Comment by sbueringer** [comment]
Verified with CoreOS 2 Masters & 1 node

**Comment by jichenjc** [comment]
ok, let's merge and do changes for ubuntu/centos together later

/lgtm
/approve

**Comment by sbueringer** [comment]
> ok, let's merge and do changes for ubuntu/centos together later
> 

yup this PR won't break much anyway :)

**Pull request merged**
