### PR TITLE
✨ Remove ensure kind binary script from repository

### LINKED ISSUE #1035: Remove ensure kind binary script from repository
/kind feature

**Describe the solution you'd like**
~~We should update kind to [v0.11.1](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1) to have at least Kubernetes v1.21.1 while we're initially deploying CAPI/CAPOCAPI to the kind cluster.~~

We're able to remove the [ensure-kind.sh](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/hack/ensure-kind.sh) script from our repository as this is obsolete. We're not using this binary anymore.

**Anything else you would like to add:**

/assign

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1035

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by tobiasgiese** [comment]
Do we even need the `ensure-kind.sh` script if we download the `kind` binary via `make -C hack/tools bin/kind`?
I think my PR is *kind* of obsolete, isn't it?

**Comment by tobiasgiese** [comment]
If the `pull-cluster-api-provider-openstack-e2e-test ` is green we don't need this binary anymore 🙂

**Comment by tobiasgiese** [comment]
> If the `pull-cluster-api-provider-openstack-e2e-test` is green we don't need this binary anymore slightly_smiling_face

🟢

**Comment by jichenjc** [comment]
/approve

seems the test doesn't need kind

**Pull request merged**
