### PR TITLE
🐛 Fix deletion of cluster when bastion image missing

### LINKED ISSUE #2266: [v0.10.6] OpenStackCluster stuck on deletion when failing to resolve bastion image
/kind bug

**What steps did you take and what happened:**

1. Create a cluster
2. Make sure bastion is enabled and using an image that doesn't exist OR a filter that selects multiple images
3. Delete the cluster
4. The cluster stays deleting forever. The OpenStackCluster cannot be deleted because CAPO cannot resolve the bastion image.

Code:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4d9dadfcc262dd1c860af1a24ec61433b0eedf21/controllers/openstackcluster_controller.go#L155-L158

**What did you expect to happen:**

**Anything else you would like to add:**

This issue is not present in v0.11.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.10.6
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

If the bastion image is missing or ambiguous, we do not have a bastion. In that case, we must continue with the deletion or be permanently stuck.

This is a direct PR for release-0.10 since the issue doesn't exist on main.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2266

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by EmilienM** [comment]
/approve
/lgtm
/cherry-pick release-0.11

Thanks!

**Comment by lentzi90** [comment]
No need to cherry-pick. This issue does not exist on release-0.11 :slightly_smiling_face:

**Pull request merged**
