### PR TITLE
🌱Release 0.7 patches

### PR DESCRIPTION
**Pull request by mdbooth**
Mechanical changes required on the creation of the 0.7 release branch.

/hold

### CODE REVIEW

**Comment by tobiasgiese** [comment]
> Is there something that might need to be updated to support https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.0 out of the box?

At least we followed the upgrade guide to v1.2 with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1302 and https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1283.
We should respect the [upgrade guide from v1.2 to v1.3](https://cluster-api.sigs.k8s.io/developer/providers/v1.2-to-v1.3.html).

I'll take a look at it 👍🏻

**Comment by mdbooth** [comment]
> Seems to be the metadata.yaml that is missing the 0.7 entry.
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3430748896a43e5bfdfaaf260f10ed6b78d7361e/test/e2e/data/shared/v1beta1_provider/metadata.yaml#L13-L15
> 
> As soon as it comes to the release itself, we should extend the README.md by `v0.7`.
> 
> What I'm concerned about:
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3430748896a43e5bfdfaaf260f10ed6b78d7361e/test/e2e/suites/e2e/clusterctl_upgrade_test.go#L34-L36
> 
> At least the comment requires the change from `v0.6` to `v0.7`. And we would accept, that we continue testing `clusterctl upgrade` with `v0.7` only.

@lentzi90 I know you worked this out. What's going to happen here?

**Comment by lentzi90** [comment]
> > Seems to be the metadata.yaml that is missing the 0.7 entry.
> > https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3430748896a43e5bfdfaaf260f10ed6b78d7361e/test/e2e/data/shared/v1beta1_provider/metadata.yaml#L13-L15
> > 
> > As soon as it comes to the release itself, we should extend the README.md by `v0.7`.
> > What I'm concerned about:
> > https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3430748896a43e5bfdfaaf260f10ed6b78d7361e/test/e2e/suites/e2e/clusterctl_upgrade_test.go#L34-L36
> > 
> > At least the comment requires the change from `v0.6` to `v0.7`. And we would accept, that we continue testing `clusterctl upgrade` with `v0.7` only.
> 
> @lentzi90 I know you worked this out. What's going to happen here?

It will still go from v0.6 to main. I should probably add a test for v0.7 to main also. If we want to go just v0.6 -> v0.7 we will need to add parameters for that in the test. It is already supported but default is to upgrade to the latest, which is main with the e2e config we have.

**Pull request merged**
