### PR TITLE
🌱 E2E: Add clusterctl upgrade test for v0.9 -> main

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

We should test upgrades from the latest release (v0.9) to main to ensure that we don't break the upgrade path.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

### CODE REVIEW

**Comment by EmilienM** [comment]
how could we miss it?
/lgtm

**Comment by EmilienM** [comment]
/hold
for CI

**Comment by lentzi90** [comment]
> how could we miss it?

Good question... I should probably add this as a post-release step in the release docs

**Comment by lentzi90** [comment]
Tests have passed, removing hold
/hold cancel

**Pull request merged**
