### PR TITLE
Output junit from ginkgo

### PR DESCRIPTION
**Pull request by mdbooth**
/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
That didn't work. Presumably there's another piece 🤔

**Comment by mdbooth** [comment]
@lentzi90 This is subterranean priority, but if you happen to know what pieces need to go together for this I'm interested to know. I'm on a slow journey towards making the e2e test output more readable!

**Comment by lentzi90** [comment]
Not sure why that didn't work. Maybe it just ends up outside of the _artifacts folder? Worth a try with `_artifacts/report.xml` I guess :shrug: 

Locally I get reports in the repo root with this:

```
export E2E_GINKGO_ARGS="--json-report=report.json --junit-report=report.xml"
make test-e2e
```

**Comment by lentzi90** [comment]
I think that's it actually! I can see the `capo-e2e-image.tar` in the artifacts (which maybe we should not put there) and how it ends up there is simply this:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/ff4c1de60c31e27f548529289b0c2f876f43a1ee/scripts/ci-e2e.sh#L89

**Pull request closed without merging**
