### PR TITLE
update test from yoga to zed in devstack

### PR DESCRIPTION
**Pull request by dulek**
**What this PR does / why we need it**:
This updates DevStack to Zed.

**Special notes for your reviewer**:

**Release note**:
```release-note

```

### CODE REVIEW

**Comment by dulek** [comment]
Looks like Ubuntu repos are returning 503. I'll wait for that to get fixed.

**Comment by dulek** [comment]
/retest

Let's see if it's not a flake.

**Comment by dulek** [comment]
@jichenjc: Please take a look at this one: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1598/pull-cluster-api-provider-openstack-e2e-test/1675813495322447872

**Comment by jichenjc** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1598/pull-cluster-api-provider-openstack-e2e-test/1675850397253636096/artifacts/devstack/controller-devstack.log

has a lot of errors like this ,I think it might indicate why we have failure? 
```

Jul 03 13:06:25 capo-e2e-controller devstack@keystone.service[101417]: [01;31mERROR keystone.server.flask.application [[01;36mNone req-8f447b10-d874-440b-ae5b-6a9d7080b767 [00;36mNone admin[01;31m] [01;35m[01;31mCould not find role: admin.[00m: keystone.exception.RoleNotFound: Could not find role: admin.
Jul 03 13:06:25 capo-e2e-controller devstack@keystone.service[101417]: ERROR keystone.server.flask.application [01;35m[00mTraceback (most recent call last):
Jul 03 13:06:25 capo-e2e-controller devstack@keystone.service[101417]: ERROR keystone.server.flask.application [01;35m[00m  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
Jul 03 13:06:25 capo-e2e-controller devstack@keystone.service[101417]: ERROR keystone.server.flask.application [01;35m[00m    rv = self.dispatch_request()

Jul 03 14:25:35 capo-e2e-controller neutron-server[138850]: ERROR oslo_messaging.rpc.server [01;35m[00mneutron_lib.exceptions.InvalidInput: Invalid input for operation: Network type value vxlan not supported, host: capo-e2e-worker with tunnel IP: 10.0.3.16.
```

thus I am wondering whether the devstack need special handling , e.g https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1597/pull-cluster-api-provider-openstack-e2e-test/1674606228522668032/artifacts/devstack/controller-devstack.log which using yoga doesn't have above error



I knew some changes recently regarding the role (https://docs.openstack.org/keystone/latest/admin/service-api-protection.html) so I guess we need re-visit the devstack setup again and at least check whether we can fix those errors ,or compare with existing functional zed env ?

by the way, seems we should try with Antolope as anyway A is the latest release already

**Comment by EmilienM** [comment]
taking over it via https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1804

**Pull request closed without merging**
