### PR TITLE
OpenstackFloatingIPPool: Adds popped ip to claimedIPs #1869 

### PR DESCRIPTION
**Pull request by bilbobrovall**
**What this PR does / why we need it**:
Adds ip to claimedIPs after it's popped from availableIPs to make sure the same IP is not added from tagged IPs when processing multiple claims in the same reconcile. 

Another would be to go back to handling one claim per reconciliation and requeuing to so claimedIPs is always populated from IPAddresses before getIP is called.

**Which issue(s) this PR fixes**:
Fixes: #1869 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:
- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by dulek** [comment]
Seems to make sense to me, if we work sequentially it should help.

Any consideration if we have multiple reconciliation threads? Do we just assume we don't?

**Comment by bilbobrovall** [comment]
> Seems to make sense to me, if we work sequentially it should help.
> 
> Any consideration if we have multiple reconciliation threads? Do we just assume we don't?

It was discussed a bit in a previous PR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1763#issuecomment-1849976633 and it was concluded that there was nothing to worry about since we have a single reconciler for the pool

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
