### PR TITLE
🐛 Fix Tilt by adding CAPO label in tilt-provider.json

### PR DESCRIPTION
**Pull request by bengentil**
**What this PR does / why we need it**:

Following https://github.com/kubernetes-sigs/cluster-api/pull/5217, tilt expects a label field in tilt-provider files

The documentation for reference: https://cluster-api.sigs.k8s.io/developer/tilt.html#tilt-provider-configuration

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
I don't use tilt. Can anybody else approve?

**Comment by jichenjc** [comment]
I don't use it as well but seems it's pretty straightforward change given the link in commit msg

/lgtm

**Comment by mdbooth** [comment]
I'm going to approve this on the basis that if it breaks somebody will come and tell us about it 😂

/approve

**Pull request merged**
