### PR TITLE
🐛Fix failing clusterctl upgrade test

### LINKED ISSUE #1658: clusterctl upgrade test broken since CAPI v1.5.0 bump
/kind bug

See e.g. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1626/pull-cluster-api-provider-openstack-e2e-full-test/1699406202267504640/build-log.txt

### PR DESCRIPTION
**Pull request by mdbooth**
Fixes #1658 

/hold

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Thanks for taking care of this!
/lgtm
I guess I should make this test run periodically so I notice when it breaks...

**Comment by mdbooth** [comment]
I don't think this was passing, yet?

**Comment by lentzi90** [comment]
No it was not.
I'm adding a periodic test here: https://github.com/kubernetes/test-infra/pull/30653

**Pull request merged**
