### PR TITLE
🏃 Update template for the external cloud provider

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This PR updates template for the external cloud provider, since #573 missed updating the template.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This PR follows up #573 

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
@jichenjc Could you review this PR? This is final missing followup of #573 .

**Comment by jichenjc** [comment]
recheck

**Pull request merged**
