### PR TITLE
 move to capi 0.3.11

### LINKED ISSUE #681: Bump CAPI to v0.3.11
/kind feature

**Describe the solution you'd like**

**Anything else you would like to add:**

https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.11

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #681

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
recheck

**Comment by hidekazuna** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Pull request merged**
