### PR TITLE
🏃 sync OWNERS and OWNERS_ALIASES for v0.5 release branch

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Syncs the OWNERS and OWNERS_ALIASES files to the same state as on master so the same who could approve to main are able to approve to the still in-use release branch.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub> Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>

### CODE REVIEW

**Review by seanschneeweiss — COMMENTED** [review]
/lgtm

**Comment by tobiasgiese** [comment]
> We have to wait for #1169 first

And we have to restart the test as #1169 is merged
/test pull-cluster-api-provider-openstack-e2e-test

**Pull request merged**
