### PR TITLE
Validate Netlify deployment after default branch change

### PR DESCRIPTION
**Pull request by tobiasgiese**
The [current Netlify deployment](https://app.netlify.com/sites/kubernetes-sigs-cluster-api-openstack/deploys) is the latest `master` commit. After this PR has been merged our Book will be updated also.

part of #855 
xref: https://github.com/kubernetes/org/issues/2883#issuecomment-956414849

### CODE REVIEW

**Comment by tobiasgiese** [comment]
The [current Netlify deployment](https://app.netlify.com/sites/kubernetes-sigs-cluster-api-openstack/deploys) is the latest `master` commit. After this PR has been merged our Book will be updated also.

**Comment by hidekazuna** [comment]
@tobiasgiese Is this PR test purpose only? Or need to be merged?

**Comment by jichenjc** [comment]
I see `tabs` added but no additional code chnages, so same questions here..

**Comment by tobiasgiese** [comment]
> The [current Netlify deployment](https://app.netlify.com/sites/kubernetes-sigs-cluster-api-openstack/deploys) is the latest `master` commit. After this PR has been merged our Book will be updated also.

See this description. We need a new commit on master to redeploy our book.
We can either wait for another PR or this one to be merged.

**Comment by jichenjc** [comment]
/lgtm

ok, I am ok to trigger this new book update ,no harm

**Comment by tobiasgiese** [comment]
> /lgtm
> 
> ok, I am ok to trigger this new book update ,no harm

Thanks 🙂 could you add the approve label as well? Reviewer and org member do not have the approve permission

**Comment by jichenjc** [comment]
thanks for raising this up :)

**Comment by tobiasgiese** [comment]
The book was already updated by #1032 🥳

**Pull request closed without merging**
