### PR TITLE
🏃 OWNERS: satisfy the maintainers tool

### LINKED ISSUE #1122: unknown field "emeritus_maintainers" in the OWNERS file
there is a [new tool](https://github.com/dims/maintainers) for parsing the kubernetes/community/sigs.yaml file and it reports an error in the OWNERS file in this repository:
> ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-aws/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"

**solution**

- rename `emeritus_maintainers` -> `emeritus_approvers`
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/OWNERS#L13

### PR DESCRIPTION
**Pull request by seanschneeweiss**
**What this PR does / why we need it**:
* remove reviewers according to [cleanup instructions](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#cleanup)
* rename emeritus_maintainers to emeritus_approvers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1122

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
thanks for the fix.

**Review by chrischdi — COMMENTED** [review]
/approve

**Comment by chrischdi** [comment]
I mean
/lgtm

Was already approved because @seanschneeweiss is maintainer/approver :-)

**Comment by seanschneeweiss** [comment]
e2e keeps failing
```
 /home/prow/go/src/sigs.k8s.io/cluster-api-provider-openstack/test/e2e/suites/e2e/e2e_suite_test.go:51
  failed to run clusterctl init
      
  Unexpected error:
      <*errors.withStack | 0xc00064cb10>: {
          error: <*errors.withMessage | 0xc00143c640>{
              cause: <*errors.withStack | 0xc00064cae0>{
                  error: <*errors.withMessage | 0xc00143c620>{
                      cause: <*runtime.missingKindErr | 0xc000eb77f0>{
                          data: "unstructured object has no kind",
                      },
                      msg: "failed to get cert-manager object /, Kind=, /",
                  },
                  stack: [0x1754f45, 0x1752bc5, 0x1756735, 0x107dadb, 0x107dbdc, 0x107db39, 0x107e51f, 0x175660c, 0x1752b25, 0x1752839, 0x17a0a5a, 0x17a759c, 0x17a8e72, 0x1870210, 0x18796b9, 0x1880025, 0x4d1505, 0x4d0a85, 0x73273a, 0x73067a, 0x730045, 0x73193e, 0x731572, 0x755b87, 0x755733, 0x7579f2, 0x763ba5, 0x7639be, 0x187d5cf, 0x513c22, 0x46b0e1],
              },
              msg: "action failed after 10 attempts",
          },
          stack: [0x1756668, 0x1752b25, 0x1752839, 0x17a0a5a, 0x17a759c, 0x17a8e72, 0x1870210, 0x18796b9, 0x1880025, 0x4d1505, 0x4d0a85, 0x73273a, 0x73067a, 0x730045, 0x73193e, 0x731572, 0x755b87, 0x755733, 0x7579f2, 0x763ba5, 0x7639be, 0x187d5cf, 0x513c22, 0x46b0e1],
      }
      action failed after 10 attempts: failed to get cert-manager object /, Kind=, /: Object 'Kind' is missing in 'unstructured object has no kind'
  occurred 
```

**Comment by apricote** [comment]
> e2e keeps failing
> 
> ```
>  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-openstack/test/e2e/suites/e2e/e2e_suite_test.go:51
>   failed to run clusterctl init
>       
>   Unexpected error:
>       <*errors.withStack | 0xc00064cb10>: {
>           error: <*errors.withMessage | 0xc00143c640>{
>               cause: <*errors.withStack | 0xc00064cae0>{
>                   error: <*errors.withMessage | 0xc00143c620>{
>                       cause: <*runtime.missingKindErr | 0xc000eb77f0>{
>                           data: "unstructured object has no kind",
>                       },
>                       msg: "failed to get cert-manager object /, Kind=, /",
>                   },
>                   stack: [0x1754f45, 0x1752bc5, 0x1756735, 0x107dadb, 0x107dbdc, 0x107db39, 0x107e51f, 0x175660c, 0x1752b25, 0x1752839, 0x17a0a5a, 0x17a759c, 0x17a8e72, 0x1870210, 0x18796b9, 0x1880025, 0x4d1505, 0x4d0a85, 0x73273a, 0x73067a, 0x730045, 0x73193e, 0x731572, 0x755b87, 0x755733, 0x7579f2, 0x763ba5, 0x7639be, 0x187d5cf, 0x513c22, 0x46b0e1],
>               },
>               msg: "action failed after 10 attempts",
>           },
>           stack: [0x1756668, 0x1752b25, 0x1752839, 0x17a0a5a, 0x17a759c, 0x17a8e72, 0x1870210, 0x18796b9, 0x1880025, 0x4d1505, 0x4d0a85, 0x73273a, 0x73067a, 0x730045, 0x73193e, 0x731572, 0x755b87, 0x755733, 0x7579f2, 0x763ba5, 0x7639be, 0x187d5cf, 0x513c22, 0x46b0e1],
>       }
>       action failed after 10 attempts: failed to get cert-manager object /, Kind=, /: Object 'Kind' is missing in 'unstructured object has no kind'
>   occurred 
> ```

This will be fixed by #1136

**Comment by mdbooth** [comment]
> > e2e keeps failing
> > ```
> >  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-openstack/test/e2e/suites/e2e/e2e_suite_test.go:51
> >   failed to run clusterctl init
> >       
> >   Unexpected error:
> >       <*errors.withStack | 0xc00064cb10>: {
> >           error: <*errors.withMessage | 0xc00143c640>{
> >               cause: <*errors.withStack | 0xc00064cae0>{
> >                   error: <*errors.withMessage | 0xc00143c620>{
> >                       cause: <*runtime.missingKindErr | 0xc000eb77f0>{
> >                           data: "unstructured object has no kind",
> >                       },
> >                       msg: "failed to get cert-manager object /, Kind=, /",
> >                   },
> >                   stack: [0x1754f45, 0x1752bc5, 0x1756735, 0x107dadb, 0x107dbdc, 0x107db39, 0x107e51f, 0x175660c, 0x1752b25, 0x1752839, 0x17a0a5a, 0x17a759c, 0x17a8e72, 0x1870210, 0x18796b9, 0x1880025, 0x4d1505, 0x4d0a85, 0x73273a, 0x73067a, 0x730045, 0x73193e, 0x731572, 0x755b87, 0x755733, 0x7579f2, 0x763ba5, 0x7639be, 0x187d5cf, 0x513c22, 0x46b0e1],
> >               },
> >               msg: "action failed after 10 attempts",
> >           },
> >           stack: [0x1756668, 0x1752b25, 0x1752839, 0x17a0a5a, 0x17a759c, 0x17a8e72, 0x1870210, 0x18796b9, 0x1880025, 0x4d1505, 0x4d0a85, 0x73273a, 0x73067a, 0x730045, 0x73193e, 0x731572, 0x755b87, 0x755733, 0x7579f2, 0x763ba5, 0x7639be, 0x187d5cf, 0x513c22, 0x46b0e1],
> >       }
> >       action failed after 10 attempts: failed to get cert-manager object /, Kind=, /: Object 'Kind' is missing in 'unstructured object has no kind'
> >   occurred 
> > ```
> 
> This will be fixed by #1136

Unfortunately not by itself. Hopefully a combination of #1136 and https://github.com/kubernetes-sigs/cluster-api/pull/6080 will do the job, though.

**Pull request merged**
