### PR TITLE
Update cluster-api version

### PR DESCRIPTION
**Pull request by YorikSar**
**What this PR does / why we need it**:

Current version of cluster-api contains issue fixed in upstream here: https://github.com/kubernetes-sigs/cluster-api/pull/698. That issue prevents clusterctl bootstrap arguments from working.

Also this update brings [kind](https://github.com/kubernetes-sigs/kind) bootstrapper which is nice.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iamemilio** [comment]
Just ran an end to end. It still seems to cause a null pointer error.

```go
[egarcia@emilio cluster-api-provider-openstack]$ cat error.txt 
I0122 20:21:02.468457       1 main.go:73] Initializing Dependencies.
W0122 20:21:02.470267       1 controller.go:58] environment variable NODE_NAME is not set, this controller will not protect against deleting its own machine
2019/01/22 20:21:02 Starting the Cmd.
I0122 20:21:02.672499       1 controller.go:114] Running reconcile Machine for openstack-master-qjhsq
I0122 20:21:02.673306       1 controller.go:89] Running reconcile Cluster for test1
I0122 20:21:02.673799       1 controller.go:127] reconciling cluster object test1 triggers idempotent reconcile.
I0122 20:21:02.674239       1 actuator.go:31] Reconciling cluster test1.
E0122 20:21:02.678603       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/golang/src/runtime/asm_amd64.s:522
/usr/lib/golang/src/runtime/panic.go:513
/usr/lib/golang/src/runtime/panic.go:82
/usr/lib/golang/src/runtime/signal_unix.go:390
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/clients/machineservice.go:104
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine/actuator.go:344
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine/actuator.go:243
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go:167
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/lib/golang/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xeb7582]

goroutine 120 [running]:
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x105c940, 0x1d24e60)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/clients.NewInstanceServiceFromMachine(0x131bfe0, 0xc0001bc2d0, 0xc00031e840, 0x0, 0x0, 0xc0004b59d8)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/clients/machineservice.go:104 +0x72
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine.(*OpenstackClient).instanceExists(0xc000119c80, 0xc00031e840, 0xc0004de001, 0x0, 0xc0003da080)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine/actuator.go:344 +0xcc
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine.(*OpenstackClient).Exists(0xc000119c80, 0x12fb9a0, 0xc00009a028, 0xc00027cd00, 0xc00031e840, 0x1, 0x0, 0x12ec1a0)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine/actuator.go:243 +0x35
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine.(*ReconcileMachine).Reconcile(0xc00030d380, 0xc0005b1329, 0x7, 0xc0005b5a00, 0x16, 0xc000546567, 0x5f5e101, 0xc000086240, 0xc000546570)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go:167 +0x362
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00014d9a0, 0x0)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207 +0x140
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x36
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003da070)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003da070, 0x3b9aca00, 0x0, 0x1, 0xc0000875c0)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0003da070, 0x3b9aca00, 0xc0000875c0)
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/egarcia/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:156 +0x357
```

**Comment by YorikSar** [comment]
@iamemilio That error is fixed in #197. I guess you need that as well to verify this PR.

**Comment by iamemilio** [comment]
Ah, I didn't know that. My mistake. I'll try with both commits

**Comment by iamemilio** [comment]
ok, /lgtm. Thanks for the patch!

**Pull request merged**
