### PR TITLE
🐛 Fix conformance tests

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

This PR fixes the conformance tests.

`Jul 19 15:46:21 cluster-conformance-t93zy8-control-plane-6wnvx cloud-init[612]: [2022-07-19 15:45:45]         [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725: output: time="2022-07-19T15:45:35Z" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725\": k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725: not found"
[...]`

xref: [cloud-final.log](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts/1549406378202763264/artifacts/clusters/bootstrap/instances/conformance-t93zy8/cluster-conformance-t93zy8-control-plane-6wnvx/cloud-final.log)
xref2: [Slack conversation](https://kubernetes.slack.com/archives/CFKJB65G9/p1658298925234219?thread_ts=1656576200.179469&cid=CFKJB65G9)

Further I fixed the previous PR #1297 by adapting https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2478

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Review by mdbooth — COMMENTED** [review]
Lets wait for the conformance test, but this lgtm.

**Comment by tobiasgiese** [comment]
Conformance test paased 👌🏻 
/unhold

**Review by seanschneeweiss — COMMENTED** [review]
/lgtm

**Pull request merged**
