### PR TITLE
install kustomize via install script instead of go get

### PR DESCRIPTION
**Pull request by sbueringer**
Fixes the kustomize installation to fix our test errors because of failed kustomize go get's

### CODE REVIEW

**Comment by ncdc** [comment]
@sbueringer you may want to look at how we do this in CAP rather than grabbing the `master` branchI:

https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/hack/tools/tools.go#L27

https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/hack/tools/go.mod#L13

https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/Makefile#L46

https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/Makefile#L111-L112

https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/Makefile#L172-L175

**Comment by sbueringer** [comment]
> @sbueringer you may want to look at how we do this in CAP rather than grabbing the `master` branchI:
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/hack/tools/tools.go#L27
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/hack/tools/go.mod#L13
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/Makefile#L46
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/Makefile#L111-L112
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/102981496ed83c2ccd8627c7832102344864669e/Makefile#L172-L175

Thx, makes sense

**Comment by sbueringer** [comment]
@ncdc okay seems to work now, can you take another look?

/assign @ncdc

**Pull request merged**
