### PR TITLE
Add providerID

### PR DESCRIPTION
**Pull request by jichenjc**
refer to aws implementation, add providerID in exists function

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
need upgrade cluster-api.......

**Comment by chrigl** [comment]
/hold

Just to not being merged accidentally. As @jichenjc mentioned... we need an update of cluster-api for this.

With having this, we might want to remove the annotation `openstack-resourceId`, because in fact this is the same.

**Comment by jichenjc** [comment]
@chrigl can you share how to upgrade cluster-api? seems change the master branch to latest commit doesn't help, should we wait for a release of cluster-api?

**Comment by chrigl** [comment]
@jichenjc We keep the master branch of `cluster-api`, since there is no release at the horizon. You could update it using `dep ensure --update sigs.k8s.io/cluster-api`... But the hard part is testing it. And please do it in a separate branch.

**Comment by jichenjc** [comment]
@chrigl because we already updated the cluster-api to branch 0.1.0 , we can remove the /hold flag here? Thanks

**Comment by frobware** [comment]
I plan to update https://github.com/kubernetes/autoscaler/pull/1866 so that mapping between nodes and machines relies solely on the ProviderID being set -- this PR would help that goal.

**Comment by chrigl** [comment]
@jichenjc Could you fit that into the refactor of #383 (which is already in master)?

**Comment by CamelCaseNotation** [comment]
What's the hold up on merging this?

**Comment by jichenjc** [comment]
we should already have this provider ID in latest code already

**Pull request closed without merging**
