### PR TITLE
🐛 api/v1beta1/openstackmachine_types.go: change errorReason/errorMessage to failureReason/failureMessage

### LINKED ISSUE #1149: 🐛 align failureReason and failureMessage also for OpenStackMachines
/kind bug

Currently, we use `failureReason` and `failureMessage` status for all CAPO resources.
Only for the `OpenStackMachines` we use `errorReason` and `errorMessage` (even the variable names are correct).

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/642d851d3068f90864fedc1a28c283f9218e3850/api/v1alpha4/openstackmachine_types.go#L109
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/642d851d3068f90864fedc1a28c283f9218e3850/api/v1alpha4/openstackmachine_types.go#L128

This should be checked with all other resources to be consistent. 

Proposed for inclusion in 0.6: #1145

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1149

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by jichenjc** [comment]
we are in beta1 already so I think we should not just do the update directly? 
instead, we should create another field something like

```
	DeprecatedFailureReason *errors.MachineStatusError `json:"errorReason,omitempty"`
	FailureReason *errors.MachineStatusError `json:"failureReason,omitempty"`
```

so we still honor both `errorReason` and `failureReason` ? 
this is my understanding of beta API version handling and happy to get any suggestions...

/hold

**Comment by tobiasgiese** [comment]
> we are in beta1 already so I think we should not just do the update directly?

I think you're totally right. We already released a v1beta1 release with v0.5.0 and thus we have to deprecate the field instead of just removing/changing it.
Should we add a note that we want to remove the deprecated field in a future release? Maybe v0.8.0?

Meanwhile I'll test the behavior of the controller if the field has changed during an update.

**Comment by tobiasgiese** [comment]
> we are in beta1 already so I think we should not just do the update directly?

I think you're totally right. We already released a v1beta1 release with v0.5.0 and thus we have to deprecate the field instead of just removing/changing it.
Should we add a note that we want to remove the deprecated field in a future release? Maybe v0.8.0?

Meanwhile I'll test the behavior of the controller if the field has changed during an update.

**Comment by apricote** [comment]
> I think you're totally right. We already released a v1beta1 release with v0.5.0 and thus we have to deprecate the field instead of just removing/changing it.

I think the v1beta1 CRD was only included in the (broken) v0.5.1 release that was cut from `main` instead of the `release-0.5` branch, `v0.5.0` and `v0.5.2` did not include the new version.

See: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/release-0.5/api

**Comment by tobiasgiese** [comment]
> I think the v1beta1 CRD was only included in the (broken) v0.5.1 release that was cut from `main` instead of the `release-0.5` branch, `v0.5.0` and `v0.5.2` did not include the new version.

Sure, that broken release totally confused me. So we made no v1beta1 release public so far. Thus our v1beta1 changes are still unstable and on our `main` branch. As this is the case we can easily change the API and add a conversion to handle the change  -- right?

**Comment by mdbooth** [comment]
> > I think you're totally right. We already released a v1beta1 release with v0.5.0 and thus we have to deprecate the field instead of just removing/changing it.
> 
> I think the v1beta1 CRD was only included in the (broken) v0.5.1 release that was cut from `main` instead of the `release-0.5` branch, `v0.5.0` and `v0.5.2` did not include the new version.
> 
> See: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/release-0.5/api

Yep, our latest release still uses v1alpha4. We're using cluster-api v1beta1. I think now is the time to make this consistent, *before* we go beta.

**Comment by jichenjc** [comment]
yes, saw the slack channel discussion, and yes, we should be able to make such change without deprecation, thanks for the discussion~

**Comment by mdbooth** [comment]
Nice. Doesn't even require an explicit conversion because we're just changing the marshalling of the new type so it happens automatically.

/lgtm

**Review by seanschneeweiss — COMMENTED** [review]
/lgtm

**Pull request merged**
