### PR TITLE
🌱 Fix conformance suite

### LINKED ISSUE #1800: Conformance tests do not run any tests
/kind bug

**What steps did you take and what happened:**

As can be seen in the [logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts/1737711524786475008#1:build-log.txt%3A1731), the conformance tests do not run any tests as it is now.

```
 Will run 0 of 0 specs
Ran 0 of 0 Specs in 0.000 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS 
```

It should definitely run some tests!

**What did you expect to happen:**

[These tests should run](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/test/e2e/suites/conformance/conformance_test.go).

**Anything else you would like to add:**

I think this is just a question of selecting tests correctly in the [config](https://github.com/kubernetes/test-infra/blob/73538ad97a1f454e05e6c31fcd74bdd7ac89efaf/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-periodics.yaml#L52-L94) or adjusting the make target or [script](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/scripts/ci-conformance.sh).

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

The conformance suite was using deprecated ginkgo v1 functionality. This commit migrates it to v2, which makes the tests run again.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1800

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

### CODE REVIEW

**Comment by EmilienM** [comment]
Thanks for working on this. Do we want to backport it to 0.11 at least?
/approve

**Comment by lentzi90** [comment]
We should probably backport it yes. I did not add conformance tests now to the periodics though. Maybe we should do that also?
/test pull-cluster-api-provider-openstack-e2e-test

**Pull request merged**
