### PR TITLE
🌱 remove apricote from reviewers

### PR DESCRIPTION
**Pull request by apricote**
**What this PR does / why we need it**:

As I announced at the Office Hours a few weeks ago, tomorrow will be my last day at $CURRENT_JOB and I won't be involved with CAPO at $NEW_JOB. Because of this I step down from my reviewers position. Thanks for the great time :)

### CODE REVIEW

**Comment by apricote** [comment]
screenshot-mean

@k8s-ci-robot this is just mean!

**Comment by jichenjc** [comment]
/lgmt
/approve

Thanks for your great help on this , good luck~

**Pull request merged**
