### PR TITLE
fix: fix typo of worker rules and controller rules

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
Fixes: #1475 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by jichenjc** [comment]
@mdbooth can you help review this? Thanks

**Review by mnaser — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by cwrau** [comment]
Sounds great! When can we expect an release? I was hoping for a quick 0.6.1?

**Comment by jichenjc** [comment]
>>>Sounds great! When can we expect a release? I was hoping for a quick 0.6.1?

I think 0.7.1 is on the way ....

**Comment by cwrau** [comment]
> > > > Sounds great! When can we expect a release? I was hoping for a quick 0.6.1?
> 
> I think 0.7.1 is on the way ....

EDIT: Sorrey, typo 😅

**Comment by cwrau** [comment]
> > > > Sounds great! When can we expect a release? I was hoping for a quick 0.6.1?
> 
> I think 0.7.1 is on the way ....

Since 0.7.1 is released but doesn't contain this fix as far as I can see, is there a timeline for 0.7.2?

**Comment by lentzi90** [comment]
I guess we can start with back porting it to the release branch. Then it will at least get included in the next patch.

/cherry-pick release-0.7

**Comment by lentzi90** [comment]
Ow sorry, it was already back-ported. Just not in the release. Then we wait I guess :slightly_smiling_face:

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1494 has been backported
I think we didn't include in 0.7.1 yet ..

**Pull request merged**
