### PR TITLE
Make hidekazuna emeritus

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/hold

### CODE REVIEW

**Comment by chrischdi** [comment]
I wish you all the best and thanks for all your contributions/revies/help/...

/lgtm

**Comment by tobiasgiese** [comment]
Thanks for all your great contributions @hidekazuna. It was a pleasure working with you

/lgtm

**Comment by mdbooth** [comment]
Thanks, @hidekazuna! I know it's not your day job, but I hope you still have a reason to stick around. It's been a pleasure to work with you.

**Comment by jichenjc** [comment]
@hidekazuna thanks for your contributions and glad to work with you :)

**Pull request merged**
