### PR TITLE
⚠️ Remove security group rules from status

### PR DESCRIPTION
**Pull request by mdbooth**
We were writing the full set of generated security rules to the status. They dominated the size of cluster object and we weren't reading them: we always fetch the current rules from OpenStack during reconciliation.

This also tweaks the rule generation code slightly, which was previously reading security group rules multiple times during a reconciliation. We now do this first and pass the result around.

Fixes: #1956

### CODE REVIEW

**Comment by huxcrux** [comment]
This looks good, skipping `/lgtm` to allow the full e2e test to run.

**Comment by mdbooth** [comment]
This is a bug in this patch:

```
  failureMessage: 'failed to reconcile security groups: unable to generate desired
    security group rules: security group k8s-cluster-e2e-bql68j-cluster-e2e-bql68j-secgroup-bastion
    not found'
```

**Comment by mdbooth** [comment]
D'oh! That's so dumb: when I was moving the code which generates `observedSecGroups` I didn't actually add the created groups to the map 🤦

We have test coverage of the various methods called by `ReconcileSecurityGroups`, but none of `ReconcileSecurityGroups` itself, so the local tests missed this. I'll see if I can add something which would have caught this.

**Comment by mdbooth** [comment]
I've fixed the bug and added some unit tests which would have triggered it.

**Pull request merged**
