### PR TITLE
📖 Add scale example

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

Add scale example to machinedeployment

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
@hidekazuna @sbueringer take a look?

**Comment by hidekazuna** [comment]
This is not cluster-api-provider-openstack specific. I think propose to Cluster API is more valuable.

Please start PR title with 📖 , as PR template suggests.

**Comment by jichenjc** [comment]
I understand, the reason why I am doing so is because:
1) avoid jump back and forth
2) has openstack unique output 
3) future potential stuffs can also be put here

**Comment by sbueringer** [comment]
I'm not sure if it's a good idea to document trivial stuff like changing replica count to 2. It's a lot of documentation for a very easy task.

**Comment by jichenjc** [comment]
ok, then, I will close this one, thanks~

**Pull request closed without merging**
