### PR TITLE
Set GO111MODULE=off when make build

### PR DESCRIPTION
**Pull request by pyama86**
**What this PR does / why we need it**:
Hi Team.
I happen trouble that set `GO111MODULE=on` on my laptop.
This is a potential problem for modern Go developers, so I want to include it in make script.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
@pyama86 please sign CLA...
also, as we are supporint go1.12 now, from https://github.com/golang/go/wiki/Modules do we really need this GO111MODULE setting?

**Comment by pyama86** [comment]
sorry,I'm signed CLA now!

> do we really need this GO111MODULE setting?

Yes,I always set `GO111MODULE=on` but, i got build error when build clustercli.

**Comment by pyama86** [comment]
Thanks!

**Pull request merged**
