### PR TITLE
🐛Fix failing clusterctl upgrade test (second attempt)

### LINKED ISSUE #1658: clusterctl upgrade test broken since CAPI v1.5.0 bump
/kind bug

See e.g. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1626/pull-cluster-api-provider-openstack-e2e-full-test/1699406202267504640/build-log.txt

### PR DESCRIPTION
**Pull request by mdbooth**
Fixes #1658

/hold

### CODE REVIEW

**Comment by lentzi90** [comment]
Oh I think I see what is going on now. In the e2e tests, we do not fetch components from github, since it is desirable to test things that are not released yet. The e2e tests are configured to create a "repository" with precisely what we need for the test based on the e2e config, instead of just fetching releases from GH. This means that if we want older versions of any provider, we must [specify that in the config](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/test/e2e/data/e2e_conf.yaml). For CAPO we already have that, but not for CAPI. For CAPI we only specify v1.5.0.

For reference, this is the folder structure and config that is created for the e2e tests: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1661/pull-cluster-api-provider-openstack-e2e-full-test/1700060262884708352/artifacts/repository/
As can be seen there, we only have CAPI v1.5.0 components available.

**Review by lentzi90 — COMMENTED** [review]
This looks correct!
/lgtm
Let's see what the CI thinks :crossed_fingers:

**Comment by mdbooth** [comment]
I think the confusion here is that we previously didn't need to update CAPI itself during this test so we didn't have separate config. Now the test doesn't work against v1.5.x, so we do need it. 🤞 this fixes it.

**Comment by lentzi90** [comment]
Where is the CAPI v1.3.6 coming from :thinking:

**Comment by mdbooth** [comment]
> Where is the CAPI v1.3.6 coming from 🤔

I think that was the previous run. The new run succeeded.

Now to see why the e2e-test failed.

**Comment by lentzi90** [comment]
Oh :facepalm: I must have missed to reload the browser tab :joy:

**Comment by mdbooth** [comment]
Probably a flake, but it looks like the failure was in cleanup:
```
I0908 12:06:23.245291       1 loadbalancer.go:503] "Deleting load balancer" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="e2e-06sftj/cluster-e2e-06sftj" namespace="e2e-06sftj" reconcileID=7c5e495a-187e-4f8b-aa1b-cd32855ad8b0 cluster="cluster-e2e-06sftj" name="k8s-clusterapi-cluster-e2e-06sftj-cluster-e2e-06sftj-kubeapi" cascade=true
I0908 12:06:23.326402       1 recorder.go:104] "events: Failed to delete load balancer k8s-clusterapi-cluster-e2e-06sftj-cluster-e2e-06sftj-kubeapi with id 7ea788ab-90ad-45ec-a50b-6726f183e730: Expected HTTP response code [202 204] when accessing [DELETE http://10.0.3.15/load-balancer/v2.0/lbaas/loadbalancers/7ea788ab-90ad-45ec-a50b-6726f183e730?cascade=true], but got 409 instead\n{\"faultcode\": \"Client\", \"faultstring\": \"Invalid state DELETED of loadbalancer resource 7ea788ab-90ad-45ec-a50b-6726f183e730\", \"debuginfo\": null}" type="Warning" object={Kind:OpenStackCluster Namespace:e2e-06sftj Name:cluster-e2e-06sftj UID:cae01ab4-a51f-47e1-88f1-d368ac7abce1 APIVersion:infrastructure.cluster.x-k8s.io/v1alpha7 ResourceVersion:9595 FieldPath:} reason="Faileddeleteloadbalancer"
E0908 12:06:23.345463       1 controller.go:324] "Reconciler error" err=<
	failed to delete load balancer: Expected HTTP response code [202 204] when accessing [DELETE http://10.0.3.15/load-balancer/v2.0/lbaas/loadbalancers/7ea788ab-90ad-45ec-a50b-6726f183e730?cascade=true], but got 409 instead
	{"faultcode": "Client", "faultstring": "Invalid state DELETED of loadbalancer resource 7ea788ab-90ad-45ec-a50b-6726f183e730", "debuginfo": null}
```

Looks like a separate bug.

**Comment by mdbooth** [comment]
The relevant test passed! e2e test failure looks like a flake.

/hold cancel

**Pull request merged**
