### PR TITLE
 📖 fix path for taggin and serverMetadata in OpenstackMachineTemplates

### LINKED ISSUE #1453: Documentation for tags/serviceMetadata in OpenstackMachineTemplate wrong
/kind bug

**What steps did you take and what happened:**
Tried to use tags and metadata for machines

**What did you expect to happen:**
Documentations is clear

**Anything else you would like to add:**

https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration.html#tagging
https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration.html#metadata

Tagging on OpenstackClusters is ok, but for Templates the fields need to be in `spec.template.spec`

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.7.0-rc.1
- Cluster-API version: 1.3.2
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by qeqar**
**What this PR does / why we need it**:
Fix documentation, for tagging and serverMetadata in OpenstackMachineTemplates

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1453

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [x] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by tobiasgiese** [comment]
/ok-to-test
/approve
/lgtm

Thanks for the documentation fix! :) 👍🏻

**Comment by qeqar** [comment]
Ok i don't see any connection between the PR and the Pipeline failure?  Can i help here?

**Comment by qeqar** [comment]
Ok, after rebase with CI fix from main, everything looks good :-)

**Pull request merged**
