### PR TITLE
📖 Update calico version in documentation

### PR DESCRIPTION
**Pull request by eratnch**
:book: Updated calico version in external-cloud-provider documentation

**What this PR does / why we need it**:
Calico version mentioned in the document is 2 releases old. Updated the same in the document.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by jichenjc** [comment]
/approve

@hidekazuna please help to lgtm, thanks

**Comment by hidekazuna** [comment]
@eratnch Calico v3.16 has been already released. Do you have a reason to stick to v3.15? Otherwise please update to 3.16.

**Comment by eratnch** [comment]
> @eratnch Calico v3.16 has been already released. Do you have a reason to stick to v3.15? Otherwise please update to 3.16.

@hidekazuna , yes i noticed that. However I wasn't sure if we always upgrade to the latest version or keep it at one previous than latest.

**Comment by hidekazuna** [comment]
@eratnch Thanks updating. FYI: current e2e test uses latest Calico v3.16.

/ok-to-test

**Comment by jichenjc** [comment]
recheck

**Comment by eratnch** [comment]
recheck

**Pull request merged**
