### PR TITLE
🐛 Bump CAPI version to fix cert-manager URL

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

The e2e tests are broken for release-0.5. Probably due to the organization change for cert-manager. By bumping the CAPI version this should be fixed.
Ref. [slack discussion](https://kubernetes.slack.com/archives/CFKJB65G9/p1646774509558269).

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
2. This is my first PR to CAPO, please tell me if there is anything I missed.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by chrischdi** [comment]
Original fix was this one: https://github.com/kubernetes-sigs/cluster-api/pull/6050/files

So I was wrong with the requirement to bump `sigs.k8s.io/cluster-api/test` , `sigs.k8s.io/cluster-api` needs to be updated but this is also done in your PR :+1:

**Comment by lentzi90** [comment]
> Original fix was this one: https://github.com/kubernetes-sigs/cluster-api/pull/6050/files
> 
> So I was wrong with the requirement to bump `sigs.k8s.io/cluster-api/test` , `sigs.k8s.io/cluster-api` needs to be updated but this is also done in your PR +1

Yeah I realized when the test failed that I needed to also update CAPI, not just the test. I guess this is because the error is coming from clusterctl, which is in CAPI (not part of the test package). Hoping it will pass this time :crossed_fingers: 
Do you want me to remove the bump for CAPI/test or is it better to bump both so they are at the same version?

**Comment by chrischdi** [comment]
I think they should be in sync so lets see how the test goes now :+1: 

Forgot to add prior to this: thank you for tackling this and the contribution :tada:

**Comment by lentzi90** [comment]
Hmm now I'm a bit lost. Still the same error. :thinking:

**Comment by mdbooth** [comment]
See #1133 which I kind of abandoned when it seemed we weren't going to use it. You'll need to bump the versions in `test/e2e/data/e2e_conf.yaml` too at a minimum.

**Comment by mdbooth** [comment]
Although you might need to bump them to 1.0.5 rather than 1.0.4, which my older patch did. Note that my PR wasn't working yet.

**Comment by chrischdi** [comment]
Yes, the old test did still ues the old version, visible in the logs via: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1169/pull-cluster-api-provider-openstack-e2e-test/1501477514122366976#1:build-log.txt%3A1485:

```
...
go: downloading k8s.io/utils v0.0.0-20210930125809-cb0fa318a74b
go: downloading sigs.k8s.io/cluster-api v1.0.1-0.20211028151834-d72fd59c8483
go: downloading sigs.k8s.io/cluster-api/test v1.0.5
go: downloading sigs.k8s.io/controller-runtime v0.10.3
go: downloading github.com/gogo/protobuf v1.3.2
...
```

:crossed_fingers:

**Comment by lentzi90** [comment]
Missed some references in the Makefile also.

**Comment by chrischdi** [comment]
Green tests :tada: 

/lgtm

**Review by mdbooth — APPROVED** [review]

**Comment by mdbooth** [comment]
We should probably fix OWNERS in the 0.5 branch if we're going to keep maintaining it.

/assign @jichenjc

**Review by seanschneeweiss — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
lending an approve until the other PR is merged :)
/approve

**Comment by jichenjc** [comment]
>>>We should probably fix OWNERS in the 0.5 branch if we're going to keep maintaining it.

do you mind add corresponding approvers through PR then we can update it ? Thanks @mdbooth

**Comment by sbueringer** [comment]
@jichenjc I think that was done in: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1170

**Comment by jichenjc** [comment]
@sbueringer thanks :)

**Pull request merged**
