### PR TITLE
e2e test: add more dump output

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
add more dumps so we can find more clue for debug

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Review by seanschneeweiss — APPROVED** [review]
Hopefully that helps :smiley:

**Comment by jichenjc** [comment]
the output can be found here 
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1304/pull-cluster-api-provider-openstack-e2e-test/1549342204546256896/artifacts/clusters/bootstrap/openstack-resources/

**Pull request merged**
