### PR TITLE
Generate-yaml sets OS_CLOUD in provider manager to the OS_CLOUD in its working env

### PR DESCRIPTION
**Pull request by iamemilio**
updates docs to explain how to set OS_CLOUD and choose your cloud.

#71

### CODE REVIEW

**Comment by iamemilio** [comment]
@chaosaffe, @flaper87  Any last words?

**Comment by Lion-Wei** [comment]
hi, @iamemilio , is this `OS_CLOUD` env only use for cloud provider?

**Comment by iamemilio** [comment]
@Lion-Wei OS_CLOUD is OpenStack specific. It is used to specify which region or cloud within a cluster you want to connect to. Does that answer your question?

**Comment by iamemilio** [comment]
Please review

**Pull request merged**
