### PR TITLE
Add more reviewers for the repository

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I5f84f77c80a10c947444219580fe2f99dda75255

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@jichenjc @gyliu513 @iamemilio @YorikSar - WDYT? Can you please let us know if you can help?

**Comment by iamemilio** [comment]
@dims yes

**Comment by gyliu513** [comment]
/lgtm

Glad to help, thanks @dims

**Comment by jichenjc** [comment]
@dims, yes glad to help ,thank you

**Comment by chrigl** [comment]
Thanks everyone!

**Pull request merged**
