### PR TITLE
 🌱 Backport E2E test fixes 

### PR DESCRIPTION
**Pull request by mdbooth**
**What this PR does / why we need it**:
This cherry picks #1412 and #1417 from main.

/hold

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]
Looking good to me!
I guess I cannot do this but anyway
/lgtm

**Comment by mdbooth** [comment]
The `pull-cluster-api-provider-openstack-e2e-full-test` job succeeded, which was the interesting one.

**Pull request merged**
