### PR TITLE
🐛 e2e: stop testing upgrades from v1alpha5 (v0.6)

### LINKED ISSUE #1885: Stop serving v1alpha5
/kind feature

Conversions from v1alpha5 have never been rigorous and are most likely broken. It is not tested.

v1alpha5 is already marked deprecated. We have previously agreed that v1alpha5 should no longer be served in CAPO v0.10, and will be removed entirely in a subsequent release, possibly as early as v0.11.

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

Since we stopped serving `v1alpha5` and has been marked as deprecated for a long time now, let's stop testing upgrades from that version.
Instead, the upgrades will be tested from v0.7 which is based on v1alpha6 up to the latest version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1885

### CODE REVIEW

**Comment by lentzi90** [comment]
I would not say this fixes #1885. That was already fixed. We just stop testing the 0.6 -> main upgrade, which is fine.

**Comment by lentzi90** [comment]
Not sure what that test failure was about. Looks like a flake to me. It got a TLS error from the webhook when applying the cluster template :shrug:

**Review by lentzi90 — COMMENTED** [review]
This looks good to me, but I wonder if we could add a v0.9 upgrade test while at it? We should anyway have an upgrade test from the latest release.

**Review by lentzi90 — COMMENTED** [review]
Actually, let's merge this and I can add the 0.9 test separatey.
/approve

**Review by mdbooth — APPROVED** [review]

**Pull request merged**
