### PR TITLE
Add Record of instance action

### LINKED ISSUE #350: event creation during create / delete machine
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

we need something like event recording so that we can 'kubectl get events' to know whether the machine is really created/deleted

later on we can extend this to more places such as machine update etc

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by jichenjc**
instance create and delete can be have some events so we can record
them and for audit purpose.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #350 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
Machine create and delete is defined in cluster-api. Why don't you implement in cluster-api?

**Comment by jichenjc** [comment]
ok, let me try to post some question there..

**Comment by jichenjc** [comment]
@hidekazuna aws implemented their own...
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/services/ec2/instances.go#L283

I created https://github.com/kubernetes-sigs/cluster-api/issues/949
for question about it..

**Comment by chaosaffe** [comment]
Even if we do log out on the controller it would certainly be great to have the event recorded on the `Machine` as well. I like the idea of pulling this up to _cluster-api as well, but we can implement it on our own for now and surface it

**Pull request merged**
