### PR TITLE
✨ Add `--version` flag

### PR DESCRIPTION
**Pull request by stephenfin**
**What this PR does / why we need it**:

Add a `--version` flag that, when used, will dump the version set on the binary. This provides a quick and easy way to check the version of the binary from the command line.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

N/A

**Special notes for your reviewer**:

N/A

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by dulek** [comment]
```
main.go:150:3: use of `fmt.Println` forbidden by pattern `^(fmt\.Print(|f|ln)|print|println)$` (forbidigo)
		fmt.Println(version.Get().String())
```

Looks like something doesn't like printing.

**Comment by stephenfin** [comment]
> I think you need to squash this before merging.

Agreed. Done now.

**Pull request merged**
