### PR TITLE
update openstack provider format from // to ///

### LINKED ISSUE #726: openstack provider ID is inconsistent to cloud provider openstack format
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack_instances.go#L304
is the format of provider `///` but we only set `//`

which means we will cause issue https://github.com/kubernetes/autoscaler/issues/3836 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #726

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
@hidekazuna can you help to review this ? Thanks

**Comment by hidekazuna** [comment]
Seems fine to fix the issue(last week I encountered the same situation!!). But I am not sure triple slash is correct for CAPI. AWS is four slash.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller_test.go#L227.

**Comment by jichenjc** [comment]
we need align with cloud provider ,as that's the `source of truth ` for openstack platform

**Comment by hidekazuna** [comment]
Double slash is true. We follow providerID of [NodeSpec](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/node-v1/#NodeSpec).
autoscaler side also follow the Node: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/clusterstate/clusterstate.go#L980-L997

We need to study more.

**Comment by jichenjc** [comment]
I understand， but cloud provider openstack didn't follow that...

**Comment by hidekazuna** [comment]
I understand triple slash is for backward compatibility in cloud provider openstack.
Let's merge.

**Pull request merged**
