### PR TITLE
Specify --metrics-bind-addr for CAPO manager

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

add --metrics-bind-addr=127.0.0.1:8080 so that capo can report metrics info
this previously exist and removed somehow..

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
Default is 127.0.0.1:10249. Do we have any reason `--metrics-bind-addr` should not to be default?

**Comment by jichenjc** [comment]
- containerPort: 8080
          name: metrics
          protocol: TCP

is in same file ...previously it's also 8080
I am ok to change to 10249 but seems capi also default to 8080

**Comment by jichenjc** [comment]
recheck

**Comment by hidekazuna** [comment]
> * containerPort: 8080
>   name: metrics
>   protocol: TCP
> 
> is in same file ...previously it's also 8080
> I am ok to change to 10249 but seems capi also default to 8080

I understand.  I wondered after checking capa source which is not have `--metrics-bind-addr`. So we have to delete containerPort to be default.

**Comment by jichenjc** [comment]
> > * containerPort: 8080
> >   name: metrics
> >   protocol: TCP
> > 
> > is in same file ...previously it's also 8080
> > I am ok to change to 10249 but seems capi also default to 8080
> 
> I understand. I wondered after checking capa source which is not have `--metrics-bind-addr`. So we have to delete containerPort to be default.

Sorry, I mean https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/manager_auth_proxy_patch.yaml#L24

**Comment by hidekazuna** [comment]
capi seems not to be 8080
https://github.com/kubernetes-sigs/cluster-api/blob/master/config/manager/manager.yaml


> > > * containerPort: 8080
> > >   name: metrics
> > >   protocol: TCP
> > > 
> > > is in same file ...previously it's also 8080
> > > I am ok to change to 10249 but seems capi also default to 8080
> > 
> > 
> > I understand. I wondered after checking capa source which is not have `--metrics-bind-addr`. So we have to delete containerPort to be default.
> 
> Sorry, I mean https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/manager_auth_proxy_patch.yaml#L24

CAPI is also.
https://github.com/kubernetes-sigs/cluster-api/blob/master/config/manager/manager_auth_proxy_patch.yaml#L24

So,
Both CAPI and CAPO has `--metrics-bind-addr` in manager_auth_proxy_patch.yaml. That is fine.
Only CAPO has containerPort: 8080 in manager.yaml. This should to be fixed.

**Comment by hidekazuna** [comment]
Thanks for you, I found another issue and raised #728 😃

**Comment by jichenjc** [comment]
recheck

**Comment by hidekazuna** [comment]
@jichenjc PTAL #729 .

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Comment by chaosaffe** [comment]
recheck

**Comment by chaosaffe** [comment]
Thanks for the patch @jichenjc

**Comment by hidekazuna** [comment]
@jichenjc `--metrics-bind-addr=127.0.0.1:8080` is added by patches:
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/manager_auth_proxy_patch.yaml#L24
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/webhook/manager_webhook_patch.yaml#L12

We do not need this PR. Actually we can get the same result using `kustomize build` under `config` directory.

**Comment by jichenjc** [comment]
> @jichenjc `--metrics-bind-addr=127.0.0.1:8080` is added by patches:
> 
> * https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/manager_auth_proxy_patch.yaml#L24
> * https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/webhook/manager_webhook_patch.yaml#L12
> 
> We do not need this PR. Actually we can get the same result using `kustomize build` under `config` directory.

are those for proxy and webhook? the PR is for the manager ..

**Comment by hidekazuna** [comment]
Patches are for manager.

```
- name: manager
        args:
        - "--metrics-bind-addr=127.0.0.1:8080"
        - "--leader-elect"
```

**Pull request merged**
