### PR TITLE
🐛 Fix go1.19 linting errors

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

Currently we're facing the following issue:

```
test/e2e/shared/suite.go:27:2: SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
```

[xref](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1312/pull-cluster-api-provider-openstack-test/1552214435383218176)

See https://github.com/go-critic/go-critic/issues/1019

Further we have to make our linter happy, because the most recent test-infra image `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220726-61b7bafca6-master` is using go1.19-rc2 (see https://github.com/kubernetes/test-infra/pull/26920)

```
❯ docker run -ti --entrypoint bash gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220726-61b7bafca6-master
[...]
root@a4f4d8285e82:/workspace# go version
go version go1.19rc2 linux/amd64
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by apricote** [comment]
/lgtm

Thanks for taking care of all these little things the last weeks @tobiasgiese !

**Comment by tobiasgiese** [comment]
/hold

We should discuss if want to fix these errors because of `golangci-lint@v1.46.2` or if we want to downgrade to `v1.44.0` (or similar).
See https://github.com/kubernetes-sigs/cluster-api/pull/6737 (thx @chrischdi)

**Review by seanschneeweiss — APPROVED** [review]
/lgtm

**Comment by seanschneeweiss** [comment]
:+1: for fixing these errors.

Should we update golangci-lint to v1.47.2 in a following PR?

**Comment by tobiasgiese** [comment]
> Should we update golangci-lint to v1.47.2 in a following PR?

I'd suggest to not update golangci-lint to v1.47.2, see https://github.com/kubernetes-sigs/cluster-api/pull/6737#issuecomment-1193964533

> v1.47.1 does not work due to performance issues in the revive linter. [v1.47.2](https://github.com/golangci/golangci-lint/releases/tag/v1.47.2) disables the problematic linters allowing that version of golangci-lint to be used on CAPI at the cost of some linter coverage.

**Comment by tobiasgiese** [comment]
But I think it's fair to fix these errors (i.e., merge this PR).
k/k is doing this as well (https://github.com/kubernetes/kubernetes/pull/111254/files)

**Pull request merged**
