### PR TITLE
✨Allow update for some param only first time update

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

Only allow the field's update at first time, as that will be updated by CAPI internally,
after that, customer's update will be rejected..

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
follow up of #1006 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by jichenjc** [comment]
@mdbooth this is follow up of #1006

**Review by mdbooth — APPROVED** [review]
Nice!

Do we have a good way to test these, yet? The E2E tests, I guess, but that seems like a big hammer.

**Comment by mdbooth** [comment]
I was thinking of [envtest](https://book.kubebuilder.io/reference/envtest.html).

To get there I think we need to merge #886, then implement interfaces for the remainder of our services (as we currently have for networking only) to allow us to cleanly mock out OpenStack calls. This will allow us to write tests like https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controllers/awsmachine_controller_test.go.

I'm not proposing we do all that before merging your patch, btw! It's going to be a lot of work.

**Pull request merged**
