### PR TITLE
Upgrade to latest CAPI version (2021-05-07)

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Prereq of: #859

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by jichenjc** [comment]
/lgtm
/hold cancel

looks good, I remember the gate will block the PR if it failed, so let's wait for e2e

**Comment by sbueringer** [comment]
Yup. Hopefully it works this time not entirely sure about kustomize

**Comment by sbueringer** [comment]
@jichenjc I backported some other changes from my cluster-api PR. The actual problem was that the kustomization.yaml did not match anymore. They seem to match with regex and `$` was a problem. So I just changed it to `.*` in the kustomization.yaml

**Pull request merged**
