### PR TITLE
 ✨ My594 revised #590 #594 wrong parameter for a user provider network

### LINKED ISSUE #590: Wrong parameter for a user provided network crashes the controller
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried to specify in openstack cluster a network (which was wrong). Not only the deployment failed but the container crashed.

**What did you expect to happen:**
Just a failed deployment.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
In openstackcluster_controller line 300, an or (||) was probably intended on the check of err and the size of the network list.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by pramchan**
✨ 
**What this PR does / why we need it**: 
To correct  the previous #594swapping ifs precedence for error check after
https://github.com/pramchan/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L300
to...
if err != nil {
return errors.Errorf("failed to find network: %v", err)
}
if len(networkList) == 0 {
return errors.Errorf("failed to find any network: %v", err)
}
if len(networkList) > 1 {
return errors.Errorf("failed to find only one network (result: %v): %v", networkList, err)
}
openStackCluster.Status.Network = &infrav1.Network{
ID: networkList[0].ID,
Name: networkList[0].Name,
}
**Which issue(s) this PR fixes** *:
Fixes #590 , #594

**Special notes for your reviewer**:
the way I did it is 
git log --oneline
c528adda (HEAD -> my594) revised #590 #594 wrong parameter for a user provider network
...
edited and added the controllers/openstackclsuater-controllers.go
...
git branch my594 c528adda
git checkout my594
git push --repo  https://github.com/pramchan/cluster-api-provider-openstack
remote: Create a pull request for 'my594' on GitHub by visiting:
remote:      https://github.com/pramchan/cluster-api-provider-openstack/pull/new/my594
remote:
To https://github.com/pramchan/cluster-api-provider-openstack
 * [new branch]        my594 -> my594
Not sure if this will do the trick. If not will close open a fresh pull as this certainly turned to be challenging with so may in between parallel  updates
.

### CODE REVIEW

**Comment by hidekazuna** [comment]
@pramchan Code itself is good to me. You can make the title and PR comment better.

This PR is to fix a bug so that :bug: should be added instead of :sparkles: at the beginning of the title.
Title is summarize this PR does for example: :bug: Return error correctly If wrong network name was given

> **What this PR does / why we need it**:

You do not need to write code itself here. Please summarize for example:
If wrong network name was given, the container crashes. This PR fixes to return error correctly.

> **Which issue(s) this PR fixes** *:
> Fixes #590 , #594

Only issue is needed so that #590 is enough.

> 
> **Special notes for your reviewer**:

You do not need to write how to create your PR here.
If you want to address #594, Say like "This replace #594 "

**Comment by hidekazuna** [comment]
@jichenjc Code itself is good to me. So,could you update PR comment? Maintainer can update PR comment.

**Comment by jichenjc** [comment]
@hidekazuna I think it would be better to ask @pramchan to update if he likes :)

**Comment by hidekazuna** [comment]
I want to merge this PR.

/lgtm

**Pull request merged**
