### PR TITLE
📖 Fix network-related docs for API v1alpha7

### PR DESCRIPTION
**Pull request by stephenfin**
**What this PR does / why we need it**:

Update the docs to reflects changes introduced in API v1alpha7. While here we also fix some other issues with the docs and bump the version of mkdocs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

n/a

**Special notes for your reviewer**:

n/a

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by stephenfin** [comment]
/retitle 📖 Fix network-related docs for API v1alpha7

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by jichenjc** [comment]
/approve 

thanks for the update

**Pull request merged**
