### PR TITLE
🏃Remove unnecessary field in manager.yaml

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This PR updates manager.yaml to match capi's manager.yaml. It is better to understand.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Review by sbueringer — APPROVED** [review]

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Comment by chaosaffe** [comment]
recheck

**Pull request merged**
