### PR TITLE
✨ Do not update fip if its already mapped correct

### LINKED ISSUE #949: Do not update floating ip if its already mapped correct
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We had problems reconciling our clusters with legacy load balancers, which were migrated from Neutron LBaaS to Octavia. The issue is that the port has no project id associated.
Therefore, a floating ip association will fail with the error:

```
Bad floatingip request: Cannot process floating IP association with Port a52bde06-ea25-4264-85b9-3af36628109b, since that port is owned by a different tenant.
```

**What did you expect to happen:**

The floating ip shouldn't be handled at all if it's already mapped.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.4.0
- Cluster-API version: v0.4.0 (latest master)
- OpenStack version: VIO 7.0
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): v1.21.3
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #949

**Special notes for your reviewer**:

A nice side effect is that we save a OpenStack API call.

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by hidekazuna** [comment]
@tobiasgiese Could you please open an issue for this PR?

**Comment by tobiasgiese** [comment]
> @tobiasgiese Could you please open an issue for this PR?

Sure, created #948

**Pull request merged**
