### PR TITLE
Update dependencies, fix things for CI job to work

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I521008f0a255141eec19503bd77f240cd9779b8d
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by m1093782566** [comment]
self assigning...

/assign

**Comment by dims** [comment]
i merged it for now @m1093782566 let's try in the next PR

**Comment by m1093782566** [comment]
assigning works now...

Trying LGTM

/lgtm

**Pull request merged**
