### PR TITLE
Trunk revert

### PR DESCRIPTION
**Pull request by luis5tb**
Problem was cluster-api-provider-openstack vendor was wrongly added

### CODE REVIEW

**Comment by flaper87** [comment]
/approve

I'll let @chaosaffe merge this one!

**Comment by chaosaffe** [comment]
/assign @chrigl
I will defer to Chris as I haven't touched this one in a while

@luis5tb sorry for the confusion, and I want to emphasize that we are very
grateful for your work! Thank you again

**Comment by luis5tb** [comment]
@chaosaffe: Thanks! And don't worry, it was a newbie mistake! Seems my go env is wrongly configured and dep ensure added the wrong vendor stuff. In the env where I was testing it it was not the case and thus I thought it was working. Sorry for the breakage!

**Comment by flaper87** [comment]
@chrigl I think @luis5tb already ran the tests you wanted. Quoting his comment on the revert PR below:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/221#issuecomment-461733127

> @chaosaffe: I tested the next 3 scenarios and they worked as expected:
> 
>     * Trunk support + trunks==true --> working
> 
>     * Trunk support + trunks==false --> working
> 
>     * No trunk support + trunks==false --> working
> 
> 
> I did not test though a kind of wrong configuration, where there is no support for trunks, but still we set it on the machine.yaml to true. In that case creation fail as expected as there is no trunk support. The problem I found is that is leaving a leftover port. I can add an extra checking in a follow up PR to avoid this situation. We have two options:
> 
>     * If there is no trunk support, fall back to trunks=false regardless of what machine.yaml says
> 
>     * if trunks=true but no trunk support, fail before creating the port, so that machine creation fail (with the right message, wrong configuration) but leaving no leftovers.
> 
> 
> I don't have strong opinions here, but I would go for the second. What do you think?

**Pull request merged**
