### PR TITLE
Transform neutron filter tags into lists

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by EmilienM** [comment]
I would have hold cancel if the upgrade patch passed but it failed and I provided a fix here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1916
Once this merge, please rebase and run the upgrade job again and if green I think this is good to go.

**Review by lentzi90 — COMMENTED** [review]
Makes sense
/approve

**Pull request merged**
