### PR TITLE
🐛 Update Ubuntu, CirrOS & Amphora image

### LINKED ISSUE #1407: Ubuntu image for e2e workload clusters is outdated
/kind bug

**What steps did you take and what happened:**

We have an issue with our ubuntu image where we're not able to update the apt sources due to outdated public keys. To fix this issue we recreate the image via image-builder.

To have updated images we can update the CirrOS image as well.

Error

```
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05 NO_PUBKEY FEEA9169307EA071
E: The repository 'https://apt.kubernetes.io/ kubernetes-xenial InRelease' is not signed.
failed 10 times: apt-get update
```

Example Prow job: [1406/pull-cluster-api-provider-openstack-e2e-test/1599665554006740992](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1406/pull-cluster-api-provider-openstack-e2e-test/1599665554006740992)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### PR DESCRIPTION
**Pull request by tobiasgiese**
We have an issue with our ubuntu image where we're not able to update the apt sources due to outdated public keys. To fix this issue we recreate the image via image-builder.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1407

The default image-builder disk size ["defaults to 20GB as of 31.10.22"](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi/packer/qemu).
Image built and uploaded with

```shell
$ PACKER_FLAGS="--var 'disk_size=10240'" make -C images/capi build-qemu-ubuntu-2004
[...]
$ file images/capi/output/ubuntu-2004-kube-v1.23.10/ubuntu-2004-kube-v1.23.10
images/capi/output/ubuntu-2004-kube-v1.23.10/ubuntu-2004-kube-v1.23.10: QEMU QCOW2 Image (v3), 10737418240 bytes
$ gcloud storage cp images/capi/output/ubuntu-2004-kube-v1.23.10/ubuntu-2004-kube-v1.23.10 gs://artifacts.k8s-staging-capi-openstack.appspot.com/test/ubuntu/2022-12-05/ubuntu-2004-kube-v1.23.10.qcow2

```

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by mdbooth** [comment]
> e2e tests still failing. Trying to revert #1301 as this PR seems to break our provisioning (see [status of this `OpenStackMacine`](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1408/pull-cluster-api-provider-openstack-e2e-test/1599777051651346432/artifacts/clusters/bootstrap/resources/e2e-43q9em/OpenStackMachine/cluster-e2e-43q9em-control-plane-pcbhd.yaml))
> 
> /hold

@tobiasgiese What's the problem there? Looks like the cause is the instance went to ERROR, right? Unless https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1301 caused the error surely the failure behaviour is correct, but I suspect I'm missing something obvious.

**Comment by tobiasgiese** [comment]
> What's the problem there? Looks like the cause is the instance went to ERROR, right? Unless #1301 caused the error surely the failure behaviour is correct, but I suspect I'm missing something obvious.

It's just the error message and that PR was merged recently. My intention was to identify the issue without a deep analysis.
But @seanschneeweiss already found the issue. It seems that it's due to the gophercloud bump.

**Comment by mnaser** [comment]
@tobiasgiese 

```
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280] Traceback (most recent call last):
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/compute/manager.py", line 2729, in _build_resources
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     yield resources
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/compute/manager.py", line 2489, in _build_and_run_instance
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     self.driver.spawn(context, instance, image_meta,
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/driver.py", line 4306, in spawn
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     created_instance_dir, created_disks = self._create_image(
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/driver.py", line 4701, in _create_image
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     created_disks = self._create_and_inject_local_root(
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/driver.py", line 4829, in _create_and_inject_local_root
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     self._try_fetch_image_cache(backend, fetch_func, context,
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/driver.py", line 10621, in _try_fetch_image_cache
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     image.cache(fetch_func=fetch_func,
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/imagebackend.py", line 274, in cache
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     self.create_image(fetch_func_sync, base, size,
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/imagebackend.py", line 643, in create_image
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     self.verify_base_size(base, size)
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]   File "/opt/stack/nova/nova/virt/libvirt/imagebackend.py", line 330, in verify_base_size
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280]     raise exception.FlavorDiskSmallerThanImage(
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280] nova.exception.FlavorDiskSmallerThanImage: Flavor's disk is too small for requested image. Flavor disk is 10737418240 bytes, image is 21474836480 bytes.
Dec 05 19:39:57 capo-e2e-controller nova-compute[143098]: ERROR nova.compute.manager [instance: 7babc98b-003d-4bc8-b56d-5de33cab9280] 
```

I'm going to guess the new image is bigger (or you provided a raw image).

**Comment by mnaser** [comment]
@tobiasgiese 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3430748896a43e5bfdfaaf260f10ed6b78d7361e/hack/ci/cloud-init/controller.yaml.tpl#L152-L155

can you bump that to 20G and I think we'll be golden

**Comment by tobiasgiese** [comment]
> I'm going to guess the new image is bigger (or you provided a raw image).

@mnaser You found the needle in the haystack. Reallyy nice catch, thanks!

The [default image-builder disk size is `20480`](https://github.com/kubernetes-sigs/image-builder/blob/9ef11e56c70a88cd2f5230f8e09912e912d9b410/images/capi/packer/qemu/packer.json#L158). Let me re-build and re-upload this image with 10240MB.

**Comment by tobiasgiese** [comment]
I added a note to the PR description with the image-builder command.

**Comment by tobiasgiese** [comment]
Uploading new image

```
$ PACKER_FLAGS="--var 'disk_size=10240'" make -C images/capi build-qemu-ubuntu-2004
[...]
$ file images/capi/output/ubuntu-2004-kube-v1.23.10/ubuntu-2004-kube-v1.23.10
images/capi/output/ubuntu-2004-kube-v1.23.10/ubuntu-2004-kube-v1.23.10: QEMU QCOW2 Image (v3), 10737418240 bytes
```

**Comment by tobiasgiese** [comment]
/retest
/hold cancel

🤞🏻

**Comment by mnaser** [comment]
I'm seeing the following now:

```
Dec 05 23:46:59 capo-e2e-controller neutron-server[130890]: ERROR oslo.messaging._drivers.impl_rabbit [-] [49f9c7d8-e8d2-4193-92ff-59f9ee3faf4f] AMQP server on 10.0.3.15:5672 is unreachable: <RecoverableConnectionError: unknown error>. Trying again in 1 seconds.: amqp.exceptions.RecoverableConnectionError: <RecoverableConnectionError: unknown error>
Dec 05 23:46:59 capo-e2e-controller neutron-server[130897]: ERROR oslo.messaging._drivers.impl_rabbit [-] [c9309b46-8f07-4cce-aef5-e532f7a3780c] AMQP server on 10.0.3.15:5672 is unreachable: <RecoverableConnectionError: unknown error>. Trying again in 1 seconds.: amqp.exceptions.RecoverableConnectionError: <RecoverableConnectionError: unknown error>
Dec 05 23:46:59 capo-e2e-controller neutron-server[130891]: ERROR oslo.messaging._drivers.impl_rabbit [-] [d95980d1-2ea1-45de-a4cf-c832f77e28db] AMQP server on 10.0.3.15:5672 is unreachable: <RecoverableConnectionError: unknown error>. Trying again in 1 seconds.: amqp.exceptions.RecoverableConnectionError: <RecoverableConnectionError: unknown error>
Dec 05 23:46:59 capo-e2e-controller neutron-server[130894]: ERROR oslo.messaging._drivers.impl_rabbit [-] [4abcacc4-0209-4b1e-9e9a-1e373a0ab86d] AMQP server on 10.0.3.15:5672 is unreachable: <RecoverableConnectionError: unknown error>. Trying again in 1 seconds.: amqp.exceptions.RecoverableConnectionError: <RecoverableConnectionError: unknown error>
Dec 05 23:46:59 capo-e2e-controller neutron-server[130892]: ERROR oslo.messaging._drivers.impl_rabbit [-] [72228d73-ec82-4233-a88f-54eba1f38baa] AMQP server on 10.0.3.15:5672 is unreachable: <RecoverableConnectionError: unknown error>. Trying again in 1 seconds.: amqp.exceptions.RecoverableConnectionError: <RecoverableConnectionError: unknown error>
Dec 05 23:46:59 capo-e2e-controller neutron-server[130888]: ERROR oslo.messaging._drivers.impl_rabbit [-] [a50e6588-e786-4ed3-af45-6b5dccaf9b18] AMQP server on 10.0.3.15:5672 is unreachable: <RecoverableConnectionError: unknown error>. Trying again in 1 seconds.: amqp.exceptions.RecoverableConnectionError: <RecoverableConnectionError: unknown error>
```

is it possible we're OOM-ing by any chance..

**Comment by mnaser** [comment]
With 64G of memory, I doubt that, also, I don't see anything in the logs showing that.

**Comment by mnaser** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/hack/ci/create_devstack.sh#L169-L170

Does it make sense for us to capture the logs for the whole system there instead of dev stack only?

**Comment by jichenjc** [comment]
>>>Does it make sense for us to capture the logs for the whole system there instead of dev stack only?

yes, we can , it's kind of trade off ..maybe we can collect all logs for this PR and see what happened (whether it's really OOM)

**Comment by tobiasgiese** [comment]
It was the image name

```
E1205 23:58:43.502565       1 controller.go:326] "Reconciler error" err="create OpenStack instance: error getting image ID: no image with the Name ubuntu-2004-kube-v1.23.10 could be found" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" openStackMachine="e2e-4xyski/cluster-e2e-4xyski-control-plane-cp5qh" namespace="e2e-4xyski" name="cluster-e2e-4xyski-control-plane-cp5qh" reconcileID=2feab7bd-f9bd-474b-8f87-6c4a00d74c68
```

renamed it to the correct filename extension (`s/qcow/qcow2/`)

**Comment by tobiasgiese** [comment]
e2e tests are green. PTAL @jichenjc @mdbooth

**Comment by mdbooth** [comment]
> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/hack/ci/create_devstack.sh#L169-L170
> 
> Does it make sense for us to capture the logs for the whole system there instead of dev stack only?

@mnaser Those logs are primarily for debugging things like this when OpenStack itself is failing. We want anything useful in achieving that. If we've identified a need for new logs lets add them. I don't think it costs us much to collect them.

**Pull request merged**
