### PR TITLE
factored out services

### PR DESCRIPTION
**Pull request by sbueringer**
These changes are heavily inspired by CAPA. They should improve the structure
of the code for the upcoming addition of multi-node control plane
support.

**What this PR does / why we need it**:
Major refactoring to provide better structure (very similar to CAPA) for future enhancements

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Implements part of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/382

**Special notes for your reviewer**:
Functionality is overall the same as before. Sorry that this are a lot of changes at once, but I'm not sure it's possible in smaller chunks

### CODE REVIEW

**Comment by jichenjc** [comment]
/lgtm

seems this make the code looks like aws code structure now and this code logic seems better than existing one.. thanks for the refactory~

**Comment by sbueringer** [comment]
> /lgtm
> 
> seems this make the code looks like aws code structure now and this code logic seems better than existing one.. thanks for the refactory~

Yup that was the idea. I wanted to cleanup before adding the stuff for HA control plane

**Comment by sbueringer** [comment]
@chrigl  Ready for merge? :)

**Comment by sbueringer** [comment]
fyi. I already created the PRs which build upon this PR. See: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/382

(I could only open them in my own repo to show the correct difs, because this PR isn't merged yet :))

**Pull request merged**
