### PR TITLE
🏃 update yq commands to support yq V4

### LINKED ISSUE #769: update yq commands in scripts file
/kind feature

**Describe the solution you'd like**
YAML processor yq have released V4 which is quite different from previous versions. We'd like to update the code of create_cloud_conf.sh and env.rc to support both new and old versions of yq.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by wuli-jessica**
**What this PR does / why we need it**:
YAML processor yq have released V4 which is quite different from previous versions. We'd like to update the code of create_cloud_conf.sh and env.rc to support both new and old versions of yq.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #769

**Release note**:

```release-note
NONE
```

/hold

### CODE REVIEW

**Comment by jichenjc** [comment]
@wuli-jessica you don't need such new PR, just re -push the old PR with change should be good enough
anyway, this works as well

**Comment by sbueringer** [comment]
/test pull-cluster-api-provider-openstack-make-conformance

Let's wait for the green test, apart from that
/lgtm

Thx! :)

**Pull request merged**
