### PR TITLE
✨ pkg/cloud/services/networking/securitygroups.go reimplement reconcilation

### LINKED ISSUE #771: Improve security group reconcilation
/kind feature

Currently the security groups get reconciled by deleting all existing rules and creating all wanted rules if only a single rule does not match (see https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/networking/securitygroups.go#L111).

If in future the hardcoded security groups get changed and capo reconciles it will delete and recreate all security group rules which may result in connection drops.

**Describe the solution you'd like**

It is possible to create two lists:
* `rulesToCreate` (desired - observed)
* `rulesToDelete` (observed - desired)

And reconcile using them by
* deleting the rules in `rulesToDelete`
* creating the rules in `rulesToCreate`
* return `rulesToCreate + (rules which are in desired and observed)` 

**Anything else you would like to add:**

-

<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Imprint</a>
</sup>

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:
Reimplements the security group reconcilation by only creating and/or
deleting the rules desired / not desired instead of deleting all and creating all rules.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #771 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

/hold

### CODE REVIEW

**Comment by chrischdi** [comment]
I had to remove the `RemoteIPPrefix: "0.0.0.0/0",` which at the end has the same result as setting nothing: allow all.

Otherwise the reconcilation is getting a `409` because it would try to create another security group rule which has the same spec.

**Comment by jichenjc** [comment]
recheck

**Comment by chrischdi** [comment]
> recheck

I'll debug it in a local devstack setup. From our environment I can see that the environment does not save the description.

**Comment by chrischdi** [comment]
I was able to fix the issue. By default there are already security group rules inside the security groups which have another description.

Because of that I changed the order to first delete not needed rules and create the new ones afterwards

**Comment by jichenjc** [comment]
reasonable change just curious about following statement, why are we creating an exactly same rule if we know 
it's same, why we will create it? 

```
I had to remove the RemoteIPPrefix: "0.0.0.0/0", which at the end has the same result as setting nothing: allow all.

Otherwise the reconcilation is getting a 409 because it would try to create another security group rule which has the same spec.
```

**Comment by sbueringer** [comment]
/retitle ✨ pkg/cloud/services/networking/securitygroups.go reimplement reconcilation

**Comment by sbueringer** [comment]
> reasonable change just curious about following statement, why are we creating an exactly same rule if we know
> it's same, why we will create it?
> 
> ```
> I had to remove the RemoteIPPrefix: "0.0.0.0/0", which at the end has the same result as setting nothing: allow all.
> 
> Otherwise the reconcilation is getting a 409 because it would try to create another security group rule which has the same spec.
> ```

I think the problem is that the deep equal does not detect that it's the same because the server will return something else compared to what we created before.

**Comment by sbueringer** [comment]
@chrischdi please rebase so that the tests are run against the new v1alpha4 master version

**Comment by chrischdi** [comment]
> > reasonable change just curious about following statement, why are we creating an exactly same rule if we know
> > it's same, why we will create it?
> > ```
> > I had to remove the RemoteIPPrefix: "0.0.0.0/0", which at the end has the same result as setting nothing: allow all.
> > 
> > Otherwise the reconcilation is getting a 409 because it would try to create another security group rule which has the same spec.
> > ```
> 
> I think the problem is that the deep equal does not detect that it's the same because the server will return something else compared to what we created before.

Exactly: on our OpenStack (which is "VMware Integrated OpenStack") the following happens:
* security groups get reconciled
  * rules get created
* security groups get reconciled again later on
  * rules previously created having `RemoteIPPrefix: "0.0.0.0/0"` will get deleted and created again, because the API returns `nil` instead of `0.0.0.0/0`.

I can see the same result when using the openstack cli and checking the output of `openstack security group rule list --debug <secgroup ID>`
  
However: I think the response of the API is still okay, because `nil` will default to `0.0.0.0/0` in the backend according the cli docs:
```
$ openstack help security group rule create | grep -e ' --remote-ip' -A 3
  --remote-ip <ip-address>
                        Remote IP address block (may use CIDR notation;
                        default for IPv4 rule: 0.0.0.0/0, default for IPv6
                        rule: ::/0)
```

It is also ok for me to revert the removal of `0.0.0.0/0` on this PR if you like me to do so :-)

**Comment by chrischdi** [comment]
> @chrischdi please rebase so that the tests are run against the new v1alpha4 master version

rebased to master :-)

**Comment by chrischdi** [comment]
recheck

**Comment by chrischdi** [comment]
Looks like we're hitting the same issues as in #779 , maybe I should wait for #759

**Comment by chrischdi** [comment]
rebased to master again to have gcp based tests

**Review by sbueringer — APPROVED** [review]
conformance test green now :)

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
> 
> 
> > > reasonable change just curious about following statement, why are we creating an exactly same rule if we know
> > > it's same, why we will create it?
> > > ```
> > > I had to remove the RemoteIPPrefix: "0.0.0.0/0", which at the end has the same result as setting nothing: allow all.
> > > 
> > > Otherwise the reconcilation is getting a 409 because it would try to create another security group rule which has the same spec.
> > > ```
> > 
> > 
> > I think the problem is that the deep equal does not detect that it's the same because the server will return something else compared to what we created before.
> 
> Exactly: on our OpenStack (which is "VMware Integrated OpenStack") the following happens:
> 
>     * security groups get reconciled
>       
>       * rules get created
> 
>     * security groups get reconciled again later on
>       
>       * rules previously created having `RemoteIPPrefix: "0.0.0.0/0"` will get deleted and created again, because the API returns `nil` instead of `0.0.0.0/0`.
> 
> 
> I can see the same result when using the openstack cli and checking the output of `openstack security group rule list --debug <secgroup ID>`
> 
> However: I think the response of the API is still okay, because `nil` will default to `0.0.0.0/0` in the backend according the cli docs:
> 
> ```
> $ openstack help security group rule create | grep -e ' --remote-ip' -A 3
>   --remote-ip <ip-address>
>                         Remote IP address block (may use CIDR notation;
>                         default for IPv4 rule: 0.0.0.0/0, default for IPv6
>                         rule: ::/0)
> ```
> 
> It is also ok for me to revert the removal of `0.0.0.0/0` on this PR if you like me to do so :-)

no need, just want to understand the logic here, all good :_)

**Comment by jichenjc** [comment]
wait for zuul job to merge

**Comment by jichenjc** [comment]
@sbueringer looks like we don't want to run openstack/check anymore as the playbook is missing
so we should go ahead merge this and overwrite the failure..

**Comment by sbueringer** [comment]
@jichenjc Yes we have to ignore the OpenLab failures for now. I'll try to remove the OpenLab ASAP after we have the ProwJob on release-0.3

**Pull request merged**
