### PR TITLE
🌱 Reduce vCPUs for e2e and conformance tests

### PR DESCRIPTION
**Pull request by tobiasgiese**
Signed-off-by: Tobias Giese <tobias.giese@mercedes-benz.com>

**What this PR does / why we need it**:

Currently we're hitting our vCPU quota for the e2e and
conformance tests. With reducing the vCPUs with the highmem
flavor for the controller we should be fine.

Issues occurred since the conformance tests are fixed.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/49ffd322aa39446591f048a42718b700d6682294/hack/ci/gce-project.sh#L29

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/test pull-cluster-api-provider-openstack-conformance-test
/hold
<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by tobiasgiese** [comment]
We have to wait until the conformance test of #1309 is done

**Comment by tobiasgiese** [comment]
/retest

Let's see if this helps... conformance test of #1309 is completed

**Comment by jichenjc** [comment]
looks reason , waiting for CI pass

**Comment by tobiasgiese** [comment]
Both jobs are running now 👍🏻 

/unhold

**Pull request closed without merging**
