### PR TITLE
update script ci-conformance.sh

### LINKED ISSUE #1800: Conformance tests do not run any tests
/kind bug

**What steps did you take and what happened:**

As can be seen in the [logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts/1737711524786475008#1:build-log.txt%3A1731), the conformance tests do not run any tests as it is now.

```
 Will run 0 of 0 specs
Ran 0 of 0 Specs in 0.000 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS 
```

It should definitely run some tests!

**What did you expect to happen:**

[These tests should run](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/test/e2e/suites/conformance/conformance_test.go).

**Anything else you would like to add:**

I think this is just a question of selecting tests correctly in the [config](https://github.com/kubernetes/test-infra/blob/73538ad97a1f454e05e6c31fcd74bdd7ac89efaf/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-periodics.yaml#L52-L94) or adjusting the make target or [script](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/scripts/ci-conformance.sh).

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by prashantrewar**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1800

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
These are our prow jobs: https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-openstack

We run the conformance tests:
* As a periodic: [periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts](https://github.com/kubernetes/test-infra/blob/cc035528282f186d6f25529ba169e5010a960908/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-periodics.yaml#L52-L94)
* As an optional presubmit: [pull-cluster-api-provider-openstack-conformance](https://github.com/kubernetes/test-infra/blob/cc035528282f186d6f25529ba169e5010a960908/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml#L90-L132)
* As a postsubmit: [ci-cluster-api-provider-openstack-conformance](https://github.com/kubernetes/test-infra/blob/cc035528282f186d6f25529ba169e5010a960908/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-postsubmits.yaml#L3-L44)

I don't understand the purpose of running this as a postsubmit, btw, although I'm still a bit unclear on the intended function of postsubmits. @lentzi90 should we delete that?

Note that in each case we invoke the test by running [`./scripts/ci-conformance.sh`](https://github.com/kubernetes/test-infra/blob/cc035528282f186d6f25529ba169e5010a960908/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml#L116-L119).

`./scripts/ci-conformance.sh` is in our repo, and ultimately invokes `make test-conformance-fast`: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/0a4899ac6ca2c36e2ca8c532fee8c2fcf97e6f94/scripts/ci-conformance.sh#L84-L87

So if we delete test-conformance-fast we'd also have to update `ci-conformance.sh`.

I'm still really interested to understand how other CAPI providers handle running the conformance tests, btw. If you have time to investigate that I'd be very grateful.

/ok-to-test
/test pull-cluster-api-provider-openstack-conformance

**Comment by lentzi90** [comment]
> I don't understand the purpose of running this as a postsubmit, btw, although I'm still a bit unclear on the intended function of postsubmits. @lentzi90 should we delete that?

Yeah I'm not sure why we have it as both postsubmit and periodic... I think we could delete the postsubmit.

> I'm still really interested to understand how other CAPI providers handle running the conformance tests, btw. If you have time to investigate that I'd be very grateful.

I looked at both CAPA and CAPZ. They seem to have a very similar conformance suite to what we have.
- There is [ci-conformance.sh](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/scripts/ci-conformance.sh)
- calling [make test-conformance](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/988d13605fce6771b8e806b8fad73b810ff8ffcc/Makefile#L442-L443) (no fast option)
- the conformance check is to [run kubetest](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/988d13605fce6771b8e806b8fad73b810ff8ffcc/test/e2e/suites/conformance/conformance_test.go#L114-L122)
- which is the [same that we do](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/f47a3e510d744686973f8b374e388cec6a73c10e/test/e2e/suites/conformance/conformance_test.go#L95-L103)

I'm not sure what our fast conformance was supposed to do but I think it is safe to delete it. CAPZ has a fast option that increases the number of ginkgo nodes and can take a different config. But this is not used in their CI.

**Comment by lentzi90** [comment]
Ah now we are getting somewhere!

```
 You're using deprecated Ginkgo functionality:
=============================================
  Measure is deprecated and has been removed from Ginkgo V2.  Any Measure tests in your spec will not run.  Please migrate to gomega/gmeasure.
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-measure
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-openstack/test/e2e/suites/conformance/conformance_test.go:54 
```

@prashantrewar can you check how [CAPA is doing this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/988d13605fce6771b8e806b8fad73b810ff8ffcc/test/e2e/suites/conformance/conformance_test.go#L114-L122)? They have a different way of doing this "measuring" and we should probably do the same.

**Comment by prashantrewar** [comment]
@lentzi90 and @mdbooth, when I replace the whole code of [conformance_test.go](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/test/e2e/suites/conformance/conformance_test.go) with [CAPA conformance_test.go code](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/988d13605fce6771b8e806b8fad73b810ff8ffcc/test/e2e/suites/conformance/conformance_test.go) after that when I run `make test-conformance` I got an error -- A BeforeSuite node failed so all tests were skipped.
```
Running Suite: capo-conformance - /home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/suites/conformance
====================================================================================================================================
Random Seed: 1704913903

Will run 1 of 1 specs
------------------------------
[SynchronizedBeforeSuite] 
/home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/suites/conformance/conformance_suite_test.go:48
  > Enter [SynchronizedBeforeSuite] TOP-LEVEL @ 01/11/24 00:42:16.352
  [2024-01-11T00:42:16+05:30] Running Node1BeforeSuite
  [2024-01-11T00:42:16+05:30] Loading the e2e test configuration from "/home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/data/e2e_conf.yaml"
  [2024-01-11T00:42:16+05:30] Finished Node1BeforeSuite
  [FAILED] in [SynchronizedBeforeSuite] - /home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/shared/suite.go:66 @ 01/11/24 00:42:16.356
  < Exit [SynchronizedBeforeSuite] TOP-LEVEL @ 01/11/24 00:42:16.356 (4ms)
[SynchronizedBeforeSuite] [FAILED] [0.004 seconds]
[SynchronizedBeforeSuite] 
/home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/suites/conformance/conformance_suite_test.go:48

  [FAILED] Invalid test suite argument. Value of environment variable OPENSTACK_CLOUD_YAML_FILE should be an existing file: ../../../../clouds.yaml
  Expected
      <string>: ../../../../clouds.yaml
  to exist
  In [SynchronizedBeforeSuite] at: /home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/shared/suite.go:66 @ 01/11/24 00:42:16.356

  Full Stack Trace
    sigs.k8s.io/cluster-api-provider-openstack/test/e2e/shared.Node1BeforeSuite(0xc000173080)
        /home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/shared/suite.go:66 +0x536
    sigs.k8s.io/cluster-api-provider-openstack/test/e2e/suites/conformance.glob..func1()
        /home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/suites/conformance/conformance_suite_test.go:49 +0x1a
    reflect.Value.call({0x20bcd60?, 0x2731d38?, 0x13?}, {0x25ef136, 0x4}, {0xc000090f20, 0x0, 0x0?})
        /usr/local/go/src/reflect/value.go:596 +0xce7
    reflect.Value.Call({0x20bcd60?, 0x2731d38?, 0x0?}, {0xc000081f20?, 0x0?, 0x0?})
        /usr/local/go/src/reflect/value.go:380 +0xb9
------------------------------
[SynchronizedAfterSuite] 
/home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/suites/conformance/conformance_suite_test.go:54
  > Enter [SynchronizedAfterSuite] TOP-LEVEL @ 01/11/24 00:42:16.356
  [2024-01-11T00:42:16+05:30] Running AllNodesAfterSuite
  bootstrap cluster proxy does not exist yet, cannot dump clusters and machines
  [2024-01-11T00:42:16+05:30] Finished AllNodesAfterSuite
  < Exit [SynchronizedAfterSuite] TOP-LEVEL @ 01/11/24 00:42:16.356 (0s)
  > Enter [SynchronizedAfterSuite] TOP-LEVEL @ 01/11/24 00:42:16.356
  [2024-01-11T00:42:16+05:30] Running Node1AfterSuite
  [2024-01-11T00:42:16+05:30] Tearing down the management cluster
  [2024-01-11T00:42:16+05:30] Finished Node1AfterSuite
  < Exit [SynchronizedAfterSuite] TOP-LEVEL @ 01/11/24 00:42:16.356 (0s)
[SynchronizedAfterSuite] PASSED [0.000 seconds]
------------------------------

Summarizing 1 Failure:
  [FAIL] [SynchronizedBeforeSuite] 
  /home/praveen/Workspace/kubernetes-sigs/cluster-api-provider-openstack/test/e2e/shared/suite.go:66

Ran 0 of 1 Specs in 0.005 seconds
FAIL! -- A BeforeSuite node failed so all tests were skipped.
--- FAIL: TestE2EConformance (0.01s)
FAIL

Ginkgo ran 1 suite in 32.994542623s

Test Suite Failed
You're using deprecated Ginkgo functionality:
=============================================
  --stream is deprecated
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed--stream

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.11.0


real    0m32.526s
user    0m11.226s
sys     0m2.119s
make: *** [Makefile:203: test-conformance] Error 1
```

**Comment by lentzi90** [comment]
Alright, instead of copy/pasting it, can you check the ginkgo docs about the deprecation and try to follow their migration suggestion. The docs are here: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-measure
If it doesn't work immediately, don't worry. Just push it here and we can try to figure it out together

**Comment by mdbooth** [comment]
FYI I've submitted a PR to remove the postsubmit here: https://github.com/kubernetes/test-infra/pull/31625

**Pull request closed without merging**
