### PR TITLE
Avoid set failMessage when bastion creation failed

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

Avoid set failMessage if create bastion failed (which we will not reconcile again)
instead, give some chance to re-create or customer might do some manual changes in order to
make cluster able to create again

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related: #1131 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Review by seanschneeweiss — COMMENTED** [review]
/lgtm

**Comment by mdbooth** [comment]
I touched on this in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1118/commits/8466ec968c9ce3c8b29d949dc43837bf5dbc8286 (which is still WIP, so please don't bother waiting for it). If you look at that commit, there are several places the bastion can set an error state on the cluster, including this one.

/lgtm

**Comment by jichenjc** [comment]
/hold cancel 

thanks for the comments~
merge this and we can use additional PR to fix any other issue

**Pull request merged**
