### PR TITLE
🐛 uplift golang and x/net

### PR DESCRIPTION
**Pull request by tuminoid**
Uplift golang to 1.19.6 and x/net to 0.7.0 due https://osv.dev/vulnerability/GO-2023-1571

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Thanks for the PR!

Could you bump golang also in the {Docker|Container}file?
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4cd95fa2a6bd0ba60faf1d5484431662df707b37/Containerfile#L27
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4cd95fa2a6bd0ba60faf1d5484431662df707b37/Dockerfile#L18

**Comment by tuminoid** [comment]
Good catch @lentzi90. Bumped those too.

**Comment by mdbooth** [comment]
Thanks. Tests pending, obviously:

/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by lentzi90** [comment]
@tuminoid could you do a PR for release-0.5 also?

**Comment by tuminoid** [comment]
Sorry @lentzi90, had a vacation. Thanks for taking care of it.

**Comment by lentzi90** [comment]
No worries :slightly_smiling_face:

**Pull request merged**
