### PR TITLE
WIP: Create secret in OpenStackCluster resource

### LINKED ISSUE #626: cluster cloud secret not moved to target cluster
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
`clusterctl move` need move objects from bootstrap cluster to target cluster 

found the cloud-config (cloud secret) not moved and lead to target cluster has error
asked https://github.com/kubernetes-sigs/cluster-api/issues/3542 and seems 
we need consider to set reference to the cloud secret..

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This commit creates a secret includes clouds.yaml and cacert in OpenStackCluster instead of secret resource.
The secret owner becomes  OpenStackCluster. It is necessary to move cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #626 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
I am testing manually but have some problems. After moving cluster, I have to edit capo-controller-manager deployment. even if no changes, cluster phase changed from Provisioning to Provisioned.

**Comment by hidekazuna** [comment]
@jichenjc Now I moved cluster successfully. Please try this PR. After refactoring(create function to create a secret), I will drop WIP.

**Comment by hidekazuna** [comment]
recheck

**Comment by jichenjc** [comment]
@hidekazuna I am asking https://github.com/kubernetes-sigs/cluster-api/issues/3603
if we can move the secret (and IMHO , it should be moved instead of being recreated) during the move 
action will that be more reasonable ? thoughts?

**Comment by hidekazuna** [comment]
@jichenjc Apart from moving, we have benefits from creating the secret by OpenStackCluster controller.  The secret owned by OpenStackCluster is deleted with cluster deletion. We do not need to delete the secret manually.

**Comment by jichenjc** [comment]
@hidekazuna when we doing the movement, I think we will also set the owner to the cluster at `cluster-api` code repo
thus we can make it transparent to capo and we can add more stuffs later if we need to make it scale

**Comment by hidekazuna** [comment]
@jichenjc I checked https://github.com/kubernetes-sigs/cluster-api/pull/3619.

If adding label `clusterctl.cluster.x-k8s.io/move: true` to the secret,  the secret moves, right?

**Comment by jichenjc** [comment]
clusterctl.cluster.x-k8s.io/move: true ==> clusterctl.cluster.x-k8s.io/move: <cluster-name>
or 
clusterctl.cluster.x-k8s.io/move: true ==> then set clusterctl.cluster.x-k8s.io/cluster-name: <cluster-name> 

I added a label to cloud config of openstack and you can see it will be moved per my current test (need further verification)
```
# ../clusterctl move --to-kubeconfig ~/.kube/config -v 10 --dry-run
No default config file available
Performing move...
********************************************************
This is a dryrun mover, will not perform any real action
********************************************************
Discovering Cluster API objects
KubeadmConfig Count=2
OpenStackMachine Count=2
KubeadmControlPlane Count=1
MachineDeployment Count=1
MachineSet Count=1
OpenStackMachineTemplate Count=2
Secret Count=8
ConfigMap Count=1
Cluster Count=1
KubeadmConfigTemplate Count=1
OpenStackCluster Count=1
Machine Count=2
Total objects Count=23
Moving Cluster API objects Clusters=1
Pausing the source cluster
Set Cluster.Spec.Paused Paused=true Cluster="capi-openstack-3" Namespace="default"
Creating target namespaces, if missing
Creating objects in the target cluster
Creating Cluster="capi-openstack-3" Namespace="default"
Creating Secret="capi-openstack-cloud-config" Namespace="default"  
```

**Comment by hidekazuna** [comment]
Nice feature. Please go on.

**Comment by hidekazuna** [comment]
We decided to use `clusterctl.cluster.x-k8s.io/move` label. See #636

**Pull request closed without merging**
