### PR TITLE
move chrischdi to emeritus_approvers

### PR DESCRIPTION
**Pull request by chrischdi**
Stepping down as maintainer due to job changes.

- [x] squashed commits

Please also see other PRs:

- https://github.com/kubernetes/k8s.io/pull/3701
- https://github.com/kubernetes/test-infra/pull/26187
- https://github.com/kubernetes/org/pull/3401

/hold

### CODE REVIEW

**Comment by apricote** [comment]
Thanks for all your work and good luck in core CAPI :)

/lgtm

**Review by mdbooth — APPROVED** [review]

**Pull request merged**
