### PR TITLE
Update flavor usage of e2e test

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

we need put without LB info into without LB bucket

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by hidekazuna** [comment]
Is this bug or refactor?

**Comment by jichenjc** [comment]
>>>Is this bug or refactor?

kind of bug, but not in real code, it's in e2e test, put logs into wrong folder ..

**Comment by jichenjc** [comment]
also , weird that don't know where we run `without lb` template
seems no special settings to make it no lb case in e2e

**Comment by hidekazuna** [comment]
Actually FlavorWithoutLB is already used in "It should be creatable and deletable": https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/test/e2e/suites/e2e/e2e_test.go#L175

This PR seems reasonable.

/lgtm

**Pull request merged**
