### PR TITLE
✨ Bump Gophercloud to v2.2.0

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

The latest stable version on October 31th 2024.

### CODE REVIEW

**Comment by mdbooth** [comment]
Can you bump it in ORC, too? Although I guess we can do that separately. 

/lgtm

**Comment by EmilienM** [comment]
> Can you bump it in ORC, too? Although I guess we can do that separately.
> 
> /lgtm

no let's do all in once. It was a miss, sorry.

**Comment by EmilienM** [comment]
taken over by a robot https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2218

**Pull request closed without merging**
