### PR TITLE
🏃 [0.2] Move ncdc to emeritus status

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Move ncdc to emeritus status

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hidekazuna** [comment]
#708 and #709 looks the same. What's the difference?

**Comment by ncdc** [comment]
@hidekazuna this one is for the `release-0.2` branch, but I accidentally missed setting the right base branch. I have updated that now.

**Comment by hidekazuna** [comment]
@ncdc Thanks, I understand.

**Comment by sbueringer** [comment]
@ncdc

okay not sure what to do with this branch. 

Our jobs deployed in Prow are incompatible with our release branch. 

So I guess the only way to get this merged is via some kind of overwrite, (which I don't have the rights to do).


On the other side as we're definitely unable to merge further PRs on this release branch I'm not entirely sure how important it is to have to OWNERS file up-to-date on this branch

**Comment by ncdc** [comment]
If it's a pain, I'd say don't worry about it and we can close it. I'll leave it up to you if that's ok?

**Comment by sbueringer** [comment]
> If it's a pain, I'd say don't worry about it and we can close it. I'll leave it up to you if that's ok?

Yeah fine for me. I'm just not really familiar with the processes. 

If I just have to contact someone with the necessary admin rights on e.g. org kubernetes-sigs, I can definitely do that.

Otherwise I would just close it :)

**Comment by ncdc** [comment]
@vincepri have any thoughts?

**Comment by sbueringer** [comment]
As I"m now repo admin I can just merge the PR, so I'll do it :)

**Pull request merged**
