### PR TITLE
🐛 Add NAMESPACE variable in cluster templates.

### LINKED ISSUE #735: ${NAMESPACE} is missing in template files
/kind bug

**What steps did you take and what happened:**

- Run `clusterctl config cluster` command with `--target-namespace`  flag.
- `namespace` is in the manifest in spite of no `${NAMESPACE}` variable in the template file.

**What did you expect to happen:**

`${NAMESPACE}` variable should be in template files explicitly.

**Anything else you would like to add:**

Cluster API recommend `${NAMESPACE}` :
https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#common-variables

[Current CAPV template](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/templates/cluster-template.yaml) has  `${NAMESPACE}`.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by prankul88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #735 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by prankul88** [comment]
recheck

**Comment by prankul88** [comment]
recheck

**Comment by prankul88** [comment]
recheck

**Comment by prankul88** [comment]
recheck

**Review by sbueringer — APPROVED** [review]

**Pull request merged**
