### PR TITLE
Fix gate issue (test failure)

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

gate test is failing ...

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

/hold

### CODE REVIEW

**Comment by sbueringer** [comment]
Probably the same here? https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/768

@prankul88 @jichenjc As we decided to wait for the v1alpha4 PR to merge with any further merges. Does it make sense to upgrade to a new v0.3.* version? I'll upgrade to a completely different and newer version. I think this PR probably only makes sense on our `release-0.3` branch.

**Comment by jichenjc** [comment]
@sbueringer currently gate has issue (test failure)
so I want to fix it and I think it's not related to v1alpha4? just some go mod clean up...

**Comment by jichenjc** [comment]
recheck

**Comment by sbueringer** [comment]
> @sbueringer currently gate has issue (test failure)
> so I want to fix it and I think it's not related to v1alpha4? just some go mod clean up...

Ah okay, so it's mostly about getting OpenLab on other PRs working again?

/lgtm

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
> 
> 
> > @sbueringer currently gate has issue (test failure)
> > so I want to fix it and I think it's not related to v1alpha4? just some go mod clean up...
> 
> Ah okay, so it's mostly about getting OpenLab on other PRs working again?
> 
> /lgtm

yes, that's the purpose..

**Pull request merged**
