### PR TITLE
🌱 Add junit formatting for unit tests

### PR DESCRIPTION
**Pull request by mdbooth**
Run `make test` with gotestsum so we can have both raw logs and junit output.

### CODE REVIEW

**Comment by mdbooth** [comment]
Example test failure output: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/2095/pull-cluster-api-provider-openstack-test/1792498916650913792

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by lentzi90** [comment]
Right we no longer auto approve. Switching to approve
/lgtm cancel
/approve

**Comment by EmilienM** [comment]
/lgtm
awesome CI feature, thanks

**Pull request merged**
