### PR TITLE
Add seanschneeweiss as reviewer

### PR DESCRIPTION
**Pull request by sbueringer**
I think  @seanschneeweiss would be a great addition to our team of reviewers. 

This is highlighted through previous contributions and PR reviews.

Thank you for all you work until now!

I would propose a lazy consensus period until Friday 28th Mai and would merge if there are no objections until then.

/hold

### CODE REVIEW

**Comment by jichenjc** [comment]
not sure why it's has invalid owner file tag?

**Comment by sbueringer** [comment]
> not sure why it's has invalid owner file tag?

Will be fixed I assume today after: https://github.com/kubernetes/org/issues/2725 is resolved

**Comment by seanschneeweiss** [comment]
Thank you very much, really appreciate being involved with this project and working together with all of you.

**Pull request merged**
