### PR TITLE
:sparkles: Add Cilium as CNI Option

### PR DESCRIPTION
**Pull request by modzilla99**
Signed-off-by: modzilla99 <justin.lamp96@gmail.com>

**What this PR does / why we need it**:
With that PR you'll be able to deploy Cilium with SecurityGroups enabled.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by jichenjc** [comment]
thanks for the PR

I am currently actually working on https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1323

so this might be follow up of that ?

**Comment by modzilla99** [comment]
Yes that would indeed be a great follow up! Will wait for your pr to be merged.

**Comment by modzilla99** [comment]
/remove-lifecycle rotten

@jichenjc hey there, sorry to bother or are there any news on different cnis?

**Comment by wwentland** [comment]
My preference would be for users to be able to configure security groups in a generic way, rather than providing specific configuration for every CNI that could be supported.

The AWS provider defines a `CNIIngressRule` which could very well serve as inspiration here.

**Comment by wwentland** [comment]
My preference would be for users to be able to configure security groups in a generic way, rather than providing specific configuration for every CNI that could be supported.

The AWS provider defines a `CNIIngressRule` which could very well serve as inspiration here for providing similar configuration.

**Comment by jichenjc** [comment]
>>>My preference would be for users to be able to configure security groups in a generic way, rather than providing specific configuration for every CNI that could be supported.

yes, I Think it's similar to #1274 , provide a config map or define a CRD ,then predefine some well known CNI like calico or clium
then let's provide options for customer to define their own as well..

**Comment by mdbooth** [comment]
Yes. Same as the last time this came up I remain opposed to merging this. We shouldn't be embedding this configuration in code. If we need to add support for another CNI, now is the time to add configuration support for that.

**Comment by EmilienM** [comment]
You'll be covered by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1826

**Pull request closed without merging**
