### PR TITLE
📖 Add documentation for creating local test environments

### PR DESCRIPTION
**Pull request by wwentland**
**What this PR does / why we need it**:

This adds additional information on how to create a test environment similar to the one used during continuous integration.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Awesome!
I think it would be nice to mention also that the scripts support GCP and AWS also, in addition to openstack :slightly_smiling_face:

**Comment by wwentland** [comment]
> Awesome! I think it would be nice to mention also that the scripts support GCP and AWS also, in addition to openstack 🙂

Sure, no problem. I've added references to the respective scripts that will be used for creating infrastructure on AWS, GCE or OpenStack  as well. 

It would ultimately be great to have an overview of all the required environment variables for all cloud providers, but I haven't tested this on AWS or GCE yet.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
