### PR TITLE
🌱 Bump CAPI to v1.8.1

### LINKED ISSUE #2144: CAPI v1.8.0-beta.0 has been released and is ready for testing
CAPI v1.8.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.8.0 release!

## For quick reference

- [CAPI v1.8.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.8.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.8.0 will be released on **Monday, 12th August 2024**.

More details of the upcoming schedule can be seen at [CAPI v1.8.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.8.md#timeline).

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

- update CAPI to 1.8.1
- update codegen && run make generate
- manager: stop using deprecated options for diagnostics
- remove TLS options, they're in CAPI now

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2144

Co-Authored-By: @mdbooth

### CODE REVIEW

**Comment by jichenjc** [comment]
changes ok so only need fix those test errors

>>> ../kube-openapi@v0.0.0-20240228011516-70dd3763d340/pkg/common/common.go:23:2: missing go.sum entry for module providing package github.com/emicklei/go-restful/v3 (imported by k8s.io/kube-openapi/pkg/common); to add:

**Comment by EmilienM** [comment]
@mdbooth ready for review, but with your PTO you might not have time to review it today. I guess this can wait.

**Comment by EmilienM** [comment]
@pierreprinetti hey, I had to rebase this one today. I could use an extra pair of eyes in case I rebased something wrong.
Thanks

**Comment by EmilienM** [comment]
This is ready to go but it won't pass the upgrade tests until we got https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2156 merged.
I suggest we wait a bit before merging this one to ensure that the bump doesn't break upgrades :sweat:

**Comment by mdbooth** [comment]
Pretty sure the error is here:
```
[FAILED] Invalid argument. input.InitWithKubernetesVersion can't be empty when calling clusterctl-upgrade spec
Expected
    <string>: 
not to be empty
```
Guessing this is either new, or wasn't previously checked.

**Comment by mdbooth** [comment]
I think we've been caught out by https://github.com/kubernetes-sigs/cluster-api/pull/10609. Before this change the test was implicity using [the value of `INIT_WITH_KUBERNETES_VERSION` in `e2e_conf.yaml`](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/a74f5ff27a7a31d3d8778a094d41d8b549e35c81/test/e2e/data/e2e_conf.yaml#L184). This is `1.30.1`. It doesn't look like `KUBERNETES_VERSION_UPGRADE_{FROM,TO}` were in use.

Incidentally this change landed in CAPI v1.8.0, so I suspect we didn't run this test before landing that bump 😬

**Comment by mdbooth** [comment]
@EmilienM We'll want to do some squashing on this PR before merging. Maybe not all the commits, but we should squash as many commits as it ends up taking to fix the upgrade test.

**Comment by mdbooth** [comment]
/lgtm

@EmilienM Suggest you self-approve this.

**Pull request merged**
