### PR TITLE
update doc for ssh key creation

### PR DESCRIPTION
**Pull request by jichenjc**
ssh key is not needed anymore ...

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
@sbueringer ,maybe you can add how to create CA in doc as well? how CA is created manually is something we need tell customer

**Comment by sbueringer** [comment]
> @sbueringer ,maybe you can add how to create CA in doc as well? how CA is created manually is something we need tell customer

Yup I can document it. Just to clarify. In my opinion the easiest way to create a CA is:
* deploy Cluster CRD
* wait 1-2 minutes
* kubectl get cluster -o json | jq '.spec....CaCert' | base64 -d

Because the cluster actuator creates all CAs for us.

**Comment by jichenjc** [comment]
> > @sbueringer ,maybe you can add how to create CA in doc as well? how CA is created manually is something we need tell customer
> 
> Yup I can document it. Just to clarify. In my opinion the easiest way to create a CA is:
> 
> * deploy Cluster CRD
> * wait 1-2 minutes
> * kubectl get cluster -o json | jq '.spec....CaCert' | base64 -d
> 
> Because the cluster actuator creates all CAs for us.

fully agree, I don't know whether user want to use their own CA instead of created one... at least we can tell them auto create is preferred (??) and tell them how to create if they want... thanks

**Comment by sbueringer** [comment]
> > > @sbueringer ,maybe you can add how to create CA in doc as well? how CA is created manually is something we need tell customer
> > 
> > 
> > Yup I can document it. Just to clarify. In my opinion the easiest way to create a CA is:
> > 
> > * deploy Cluster CRD
> > * wait 1-2 minutes
> > * kubectl get cluster -o json | jq '.spec....CaCert' | base64 -d
> > 
> > Because the cluster actuator creates all CAs for us.
> 
> fully agree, I don't know whether user want to use their own CA instead of created one... at least we can tell them auto create is preferred (??) and tell them how to create if they want... thanks

And with create your own you mean a few openssl commands to generate the ca and a private key and how to put them into the Cluster CRD, right?

**Comment by jichenjc** [comment]
yes,that's my asking about.. thanks

**Pull request merged**
