### PR TITLE
🌱 Standardize api import aliases

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

This PR standardizes our API import aliases. Further, it removes to skip lint our conversion.go files.
Adopted from https://github.com/kubernetes-sigs/cluster-api/pull/5830 
Follow-up of Slack discussion https://kubernetes.slack.com/archives/CFKJB65G9/p1639063415164300

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Review by seanschneeweiss — COMMENTED** [review]
/lgtm
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by tobiasgiese** [comment]
I need also an approve, as this PR was created before I was added to the maintainers list 😿 

/hold cancel

**Comment by jichenjc** [comment]
/approve 

2 lgtm now ~

**Pull request merged**
