### PR TITLE
✨ Add webhook readiness and health checks

### LINKED ISSUE #954: Add webhook health check
/kind feature

**Describe the solution you'd like**
It would be nice if the controller health checks would use the readiness of the webhook server (instead of the no-op Ping).

For reference, the implementation in cluster-api: https://github.com/kubernetes-sigs/cluster-api/pull/4989

**Anything else you would like to add:**
This requires at least controller-runtime v0.9.3.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by tobiasgiese**
Signed-off-by: Tobias Giese <tobias.giese@daimler.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #954

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by chrischdi** [comment]
/retitle ✨ Add webhook readiness and health check

**Comment by chrischdi** [comment]
/retitle sparkles Add webhook readiness and health checks

**Comment by chrischdi** [comment]
/retitle ✨ Add webhook readiness and health checks

**Comment by jichenjc** [comment]
/approve

/hold cancel

already 2 lgtm

**Pull request merged**
