### PR TITLE
🐛 PR for final bugfixes before the v1alpha3 release

### PR DESCRIPTION
**Pull request by sbueringer**
* Related PRs:
  * [x] [✨ Add CAPO to clusterctl embedded metadata](https://github.com/kubernetes-sigs/cluster-api/pull/2719)
  * [ ] [[WIP] 📖 update OpenStack prerequisites in the ClusterAPI book #2683](https://github.com/kubernetes-sigs/cluster-api/pull/2683)
    * Impeded by:
      * [ ] [Add Ubuntu 18.04 QEMU image for Cluster API ](https://github.com/kubernetes-sigs/image-builder/pull/169)

Some explanations:
* Makefile: removed default values to force that values for OPENSTACK_CONTROLPLANE_IP and OPENSTACK_DNS_NAMESERVERS must be set (when using the create-cluster target)
* RELEASE.md: just some updates from creating & testing the rc.0 release
* metadata.yaml: Is required for clusterctl <= 0.3.1 because there was no embedded metadata for CAPO in these versions (see PR linked above)
* templates/env.rc:
  * replaced exit with return so that the shell does not terminate when the rc script fails :)
  * renamed vars: There were some clashes because the USERNAME var was overriden from the environment when sourcing the script. So I prefixed all of them

/hold

### CODE REVIEW

**Comment by prankul88** [comment]
Also, link https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/k8s-staging-capi-openstack/manifest.yaml
Has moved to https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/manifests/k8s-staging-capi-openstack/promoter-manifest.yaml

**Comment by sbueringer** [comment]
> Also, link https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/k8s-staging-capi-openstack/manifest.yaml
> Has moved to https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/manifests/k8s-staging-capi-openstack/promoter-manifest.yaml

Thx fixed. This I also fixed the link to: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-cluster-api.yaml

The link is not broken yet but I have an open PR to move our image push build to the same files as all other providers

**Comment by prankul88** [comment]
@sbueringer Are you planning to first open a PR to add Openstack in clusterctl pre-defined provider list and merge this latter?
Or would rather merge this first?

**Comment by sbueringer** [comment]
@prankul88 in parallel we have to assume somebody is using clusterctl 0.3.1 or below. I would keep the metadata.yaml for all our 0.3.* releases.

With the metadata.yaml in the release attachments capo RC.0 is already compatible right now

**Comment by prankul88** [comment]
@sbueringer Great. Makes sense :)

**Comment by sbueringer** [comment]
> @sbueringer Great. Makes sense :)

I listed the related PRs now above :)

**Comment by sbueringer** [comment]
@hidekazuna A colleague of mine had the same problem as you with yq. In his case it was not the python version but a newer version of the Go yq. I ammended the script to handle `""` and `"null"` the same way

**Comment by sbueringer** [comment]
@hidekazuna @jichenjc @prankul88 

If it's okay for you, I would merge this PR and create a v0.3.0 release. The rc.0 looks good to me.

I would:
* merge this PR
* create a 0.3.0 release
* afterwards merge the PR in the ClusterAPI book (I might have to adjust the book PR a bit depending on if the qemu PR in the image-builder repo is merged)

**Comment by jichenjc** [comment]
/lgtm

let's merge and move forward

**Pull request merged**
