### PR TITLE
🌱 Update golangci-lint (v1.46.2 -> v1.50.0), remove deprecated linters

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

* Updates golangci-lint version (v2.46.2 -> v1.49.0)
* Removed deprecated linters and configuration
  * deadcode
  * ifshort
  * structcheck
  * varcheck
* Fixes or adds `//nolint`s.  

/hold

### CODE REVIEW

**Comment by seanschneeweiss** [comment]
Can you adopt the title and replace v2.46.2 with v1.46.2.

Maybe we can also enable some linters as they did in CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/7208

**Comment by tobiasgiese** [comment]
/title 🌱 Update golangci-lint (v2.46.2 -> v2.49.0), remove deprecated linters

**Comment by tobiasgiese** [comment]
/retitle 🌱 Update golangci-lint (v2.46.2 -> v2.49.0), remove deprecated linters

**Comment by tobiasgiese** [comment]
/retitle 🌱 Update golangci-lint (v1.46.2 -> v1.49.0), remove deprecated linters

**Comment by oscr** [comment]
It's not easy with all the different version numbers :sweat: Thanks for the fix @tobiasgiese :rocket:

**Comment by oscr** [comment]
Just bumped the `golangci-lint` version since a new version has been released since the pr was created.

**Comment by tobiasgiese** [comment]
> Maybe we can also enable some linters as they did in CAPI: [kubernetes-sigs/cluster-api#7208](https://github.com/kubernetes-sigs/cluster-api/pull/7208)

@oscr Can you say something about the question from @seanschneeweiss?

**Comment by mdbooth** [comment]
> > Maybe we can also enable some linters as they did in CAPI: [kubernetes-sigs/cluster-api#7208](https://github.com/kubernetes-sigs/cluster-api/pull/7208)
> 
> @oscr Can you say something about the open suggestion from @seanschneeweiss?

@tobiasgiese I saw that but thought they could be added separately. Would you like me to remove the approve until it's answered?

**Comment by tobiasgiese** [comment]
> Would you like me to remove the approve until it's answered?

It's okay for me to keep the approve label. If @oscr wants to remove the `hold` and create a follow-up PR it's totally fine for me :)

**Comment by oscr** [comment]
@tobiasgiese @mdbooth Thank you for pointing out the question. To be honest I just missed it. I suggest enabling additional linters in a separate pr. Some of them give a lot of findings. However I would be glad to do it.

**Comment by tobiasgiese** [comment]
Thanks for the clarification @oscr 🙂 
/hold cancel

**Pull request merged**
