### PR TITLE
✨ Add OpenStackClusterTemplates Type

### LINKED ISSUE #931: Add OpenStackClusterTemplate type
/kind feature

**Describe the solution you'd like**
Add a new CRD named OpenStackClusterTemplate. This is needed for ClusterClass.
In the short term this type will not be used outside of ClusterClass.

xref [DockerClusterTemplate](https://github.com/kubernetes-sigs/cluster-api/issues/4900)
also see https://kubernetes.slack.com/archives/C8TSNPY4T/p1625767242134600

### PR DESCRIPTION
**Pull request by tobiasgiese**
Signed-off-by: Tobias Giese <tobias.giese@daimler.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #931

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by tobiasgiese** [comment]
Still the same error

```
ERROR: (gcloud.compute.networks.describe) Could not fetch resource:
```

/test pull-cluster-api-provider-openstack-e2e-test

**Comment by tobiasgiese** [comment]
e2e tests are green and commits are squashed

**Comment by tobiasgiese** [comment]
I think I will stop retesting until someone reviewed it :)
If findings have to be committed, a retest has to be done anyway

**Comment by tobiasgiese** [comment]
@jichenjc @chrischdi can you please take a look here? Thanks :)

**Comment by sbueringer** [comment]
@tobiasgiese I would recommend watching https://github.com/kubernetes-sigs/cluster-api/pull/4903 and waiting with merge. It probably makes sense to e.g. also implement webhooks already here.

**Comment by tobiasgiese** [comment]
@sbueringer should now be ready for review - even if https://github.com/kubernetes-sigs/cluster-api/pull/4903 is not merged yet

**Comment by sbueringer** [comment]
@jichenjc I would also like to merge that one before the release if it's okay for you. Makes it possible to use CAPO v0.4.0 with ClusterClass once it's implemented in CAPI.

/lgtm
/approve

**Comment by jichenjc** [comment]
/hold cancel

let's merge this and continue the release ,appreciate the help! 
@tobiasgiese

**Pull request merged**
