### PR TITLE
🏃 devstack: Allow empty private SSH key

### PR DESCRIPTION
**Pull request by mdbooth**
This allows use of a private key stored on a hardware token.

/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
Looks like I'm going to have to make this configurable.

**Comment by jichenjc** [comment]
/lgtm

though I am not sure the use case for it, but no harm seems

**Comment by mdbooth** [comment]
> /lgtm
> 
> though I am not sure the use case for it, but no harm seems

I need it to use the key on my Yubikey :) There's no private key file. To specify a particular key you specify the public key instead. Actual operations involving the private key happen directly on the hardware token, which SSH accesses via ssh-agent.

Yeah, it's pretty niche 😂

/hold cancel

**Comment by jichenjc** [comment]
ok, thanks for the info , this make sense 
just involved in `Yubikey` discussion somewhere else so a good timing for me to do some homework :)

**Pull request merged**
