### PR TITLE
Add lentzi90 to cluster-api-openstack-maintainers

### PR DESCRIPTION
**Pull request by mdbooth**
/hold

### CODE REVIEW

**Comment by tobiasgiese** [comment]
/lgtm

Welcome @lentzi90! 🥳

**Comment by mdbooth** [comment]
@lentzi90 I'll let you remove the hold on this if you're happy with it.

**Comment by lentzi90** [comment]
Thank you! :blush: 
/hold cancel

**Comment by tuminoid** [comment]
Congrats @lentzi90 !

**Pull request merged**
