### PR TITLE
switch to no-admin for CI test

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
@jichenjc  Test failed as I expected. In https://logs.openlabtesting.org/logs/06/606/c402fbef1bdc5f4d5f435f2cfc93930bd77042d0/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/d82ce5b/logs/_artifacts/logs/clusterapi-control-plane/containers/capo-controller-manager-86b48ddf4-tjl6n_capo-system_manager-5d9738f77f86d9cb3d8d2606478d6148ea9d37222b5d342afe1b2d3d6a05c4d2.log:
```bash
2020-08-04T02:30:26.449096803Z stderr F I0804 02:30:26.448870       1 floatingip.go:33] controllers/OpenStackMachine "msg"="Creating floating ip" "cluster"="capi-quickstart" "machine"="capi-quickstart-control-plane-m2h7h" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-control-plane-7p5k8" "ip"="172.24.5.24"
2020-08-04T02:30:26.496672905Z stderr F E0804 02:30:26.496365       1 openstackmachine_controller.go:394] controllers/OpenStackMachine "msg"="FloatingIP cannot be reconciled: error creating floatingIP: error allocating floating IP: Request forbidden: [POST http://192.168.0.3:9696/v2.0/floatingips], error message: {\"NeutronError\": {\"type\": \"PolicyNotAuthorized\", \"message\": \"(rule:create_floatingip and rule:create_floatingip:floating_ip_address) is disallowed by policy\", \"detail\": \"\"}}" "error"="UpdateError" "cluster"="capi-quickstart" "machine"="capi-quickstart-control-plane-m2h7h" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-control-plane-7p5k8" 
```

Non admin user can not create floating IP with IP address. That is why I proposed #573 .

**Comment by hidekazuna** [comment]
> @jichenjc Test failed as I expected. In https://logs.openlabtesting.org/logs/06/606/c402fbef1bdc5f4d5f435f2cfc93930bd77042d0/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/d82ce5b/logs/_artifacts/logs/clusterapi-control-plane/containers/capo-controller-manager-86b48ddf4-tjl6n_capo-system_manager-5d9738f77f86d9cb3d8d2606478d6148ea9d37222b5d342afe1b2d3d6a05c4d2.log:
> 
> ```shell
> 2020-08-04T02:30:26.449096803Z stderr F I0804 02:30:26.448870       1 floatingip.go:33] controllers/OpenStackMachine "msg"="Creating floating ip" "cluster"="capi-quickstart" "machine"="capi-quickstart-control-plane-m2h7h" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-control-plane-7p5k8" "ip"="172.24.5.24"
> 2020-08-04T02:30:26.496672905Z stderr F E0804 02:30:26.496365       1 openstackmachine_controller.go:394] controllers/OpenStackMachine "msg"="FloatingIP cannot be reconciled: error creating floatingIP: error allocating floating IP: Request forbidden: [POST http://192.168.0.3:9696/v2.0/floatingips], error message: {\"NeutronError\": {\"type\": \"PolicyNotAuthorized\", \"message\": \"(rule:create_floatingip and rule:create_floatingip:floating_ip_address) is disallowed by policy\", \"detail\": \"\"}}" "error"="UpdateError" "cluster"="capi-quickstart" "machine"="capi-quickstart-control-plane-m2h7h" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-control-plane-7p5k8" 
> ```
> 
> Non admin user can not create floating IP with IP address. That is why I proposed #573 .

#573 has been merged. But #573 does not update non lb template and e2e test, I proposed #608 . After #608, let's revisit this PR.

**Comment by hidekazuna** [comment]
> Please remove L77:
> 
> ```
> export OPENSTACK_CONTROLPLANE_IP="172.24.5.24"
> ```

Sorry this was already removed by #608.

**Comment by hidekazuna** [comment]
recheck

**Comment by hidekazuna** [comment]
recheck

**Comment by hidekazuna** [comment]
recheck

**Comment by jichenjc** [comment]
@hidekazuna seems the test passed, really weird ,maybe because the CI doesn't create floating ip now?

**Comment by hidekazuna** [comment]
> 
> 
> @hidekazuna seems the test passed, really weird ,maybe because the CI doesn't create floating ip now?

@jichenjc  CI still create floating IP, but without IP address now. non-admin user can create floating IP without IP address.

**Comment by jichenjc** [comment]
@hidekazuna so we should document what's needed for non-admin and that's enough, correct?

**Comment by hidekazuna** [comment]
> 
> 
> @hidekazuna so we should document what's needed for non-admin and that's enough, correct?

@jichenjc we are already documented [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/configuration.md#floating-ip)

```
A floating IP is automatically created and associated with the load balancer or controller node
```

**Comment by jichenjc** [comment]
so we should go ahead and use `demo` instead of `admin` in the CI test ? 
seems we document it and we made CI pass already

**Comment by hidekazuna** [comment]
> 
> 
> so we should go ahead and use `demo` instead of `admin` in the CI test ?
> seems we document it and we made CI pass already

Yes, let's merge this PR.

**Comment by jichenjc** [comment]
I updated the title, so please help to merge this

**Pull request merged**
