### PR TITLE
✨ Allow for omitting AZ from control plane nodes

### LINKED ISSUE #1252: Allow clusters without explicit availability zones
/kind feature

**Describe the solution you'd like**

Currently, CAPO machines require that a failure domain (availability zone) is specified. However there are a number of cases where this results in a sub-optimal user experience, IMHO.

In my particular target case, we are using traits, flavors, host aggregates and project isolation filters to ensure that VMs land on hypervisors that the project is permitted to use and/or have particular specialist hardware and connectivity. This works best when an AZ is not specified, as that allows Nova to pick a suitable host without constraints.

However the operator still wants to use AZs as a housekeeping thing, e.g. corresponding to racks, so they can quickly see what is scheduled where.

Because CAPO requires AZs to be specified, this means that when using CAPI/O users have to make sure that the flavor and AZ that they choose are compatible. This leads to a lot of mistakes leading to "no valid host" errors that we then have to deal with as support. We would prefer not to specify the AZ and let Nova deal with it.

We also have ambitions to use Blazar to control access to resources, in which case it will be even more important that Nova is in full control of the scheduling.

**Anything else you would like to add:**

We should still use a server group with soft anti-affinity to ensure control plane hosts are scheduled on different hypervisors when possible. This can be used whether specifying explicit AZs or not, but becomes more important in the non-explicit case.

### PR DESCRIPTION
**Pull request by mkjpryor**
**What this PR does / why we need it**:

Allows control plane nodes to be created that do not specify a failure domain (availability zone). This is important for clouds that rely on other Nova scheduler features for placement, e.g. host aggregates, project isolation filters, flavor traits.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1252 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by mkjpryor** [comment]
@mdbooth I finally got round to redoing this PR by setting the flag instead of not reporting AZs at all.

**Comment by mkjpryor** [comment]
@jichenjc 

I am trying to run `make generate` to fix the test error, and it keeps trying to remove the `Convert_v1alpha6_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec` function. Any idea why?

```
$ make verify-gen
/Library/Developer/CommandLineTools/usr/bin/make generate-go
/Library/Developer/CommandLineTools/usr/bin/make -B hack/tools/bin/controller-gen hack/tools/bin/conversion-gen hack/tools/bin/defaulter-gen
make -C hack/tools bin/controller-gen
mkdir -p bin
go build -tags=tools -o bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
make -C hack/tools bin/conversion-gen
mkdir -p bin
go build -tags=tools -o bin/conversion-gen k8s.io/code-generator/cmd/conversion-gen
make -C hack/tools bin/defaulter-gen
mkdir -p bin
go build -tags=tools -o bin/defaulter-gen k8s.io/code-generator/cmd/defaulter-gen
hack/tools/bin/controller-gen \
                paths=./api/... \
                object:headerFile=./hack/boilerplate/boilerplate.generatego.txt
hack/tools/bin/conversion-gen \
                --input-dirs=./api/v1alpha3 \
                --input-dirs=./api/v1alpha4 \
                --input-dirs=./api/v1alpha5 \
                --input-dirs=./api/v1alpha6 \
                --output-file-base=zz_generated.conversion \
                --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
E0808 09:19:11.926895   92381 conversion.go:756] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha6.OpenStackClusterSpec -> ./api/v1alpha5.OpenStackClusterSpec
E0808 09:19:11.927014   92381 conversion.go:757]   the following fields need manual conversion:
E0808 09:19:11.927017   92381 conversion.go:759]       - ControlPlaneOmitAvailabilityZone
go generate ./...
/Library/Developer/CommandLineTools/usr/bin/make generate-manifests
hack/tools/bin/controller-gen \
                paths=./api/... \
                crd:crdVersions=v1 \
                output:crd:dir=config/crd/bases \
                output:webhook:dir=config/webhook \
                webhook
hack/tools/bin/controller-gen \
                paths=./controllers/... \
                output:rbac:dir=config/rbac \
                rbac:roleName=manager-role
diff --git a/api/v1alpha5/zz_generated.conversion.go b/api/v1alpha5/zz_generated.conversion.go
index 26249eae..875b7030 100644
--- a/api/v1alpha5/zz_generated.conversion.go
+++ b/api/v1alpha5/zz_generated.conversion.go
@@ -856,11 +856,6 @@ func autoConvert_v1alpha6_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(
        return nil
 }
 
-// Convert_v1alpha6_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec is an autogenerated conversion function.
-func Convert_v1alpha6_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(in *v1alpha6.OpenStackClusterSpec, out *OpenStackClusterSpec, s conversion.Scope) error {
-       return autoConvert_v1alpha6_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(in, out, s)
-}
-
 func autoConvert_v1alpha5_OpenStackClusterStatus_To_v1alpha6_OpenStackClusterStatus(in *OpenStackClusterStatus, out *v1alpha6.OpenStackClusterStatus, s conversion.Scope) error {
        out.Ready = in.Ready
        out.Network = (*v1alpha6.Network)(unsafe.Pointer(in.Network))
generated files are out of date, run make generate
make: *** [verify-gen] Error 1
```

**Comment by mkjpryor** [comment]
@jichenjc @mdbooth @apricote @tobiasgiese 

I am still having issues with the code generation above. I think maybe I am not understanding exactly what needs to be done when a new field is added... Any advice would be greatly appreciated!

**Comment by apricote** [comment]
> I am still having issues with the code generation above. I think maybe I am not understanding exactly what needs to be done when a new field is added... Any advice would be greatly appreciated!

This is to be expected. `conversion-gen` recognizes that it can not automatically generate the full conversion, and adds a comment saying as much to `autoConvert...`:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/8b988a2a028828e2d4055a91758086dda26ef547/api/v1alpha5/zz_generated.conversion.go#L853

At that point, we need to implement a custom `Convert_...` and `conversion-gen` helpfully removes the default it generates (otherwise this would cause conflicts!). You can check out an example of these custom `Convert_` functions in `v1alpha4`:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4975828973c3b8e704302ae3417f2ca026ec750e/api/v1alpha4/openstackcluster_conversion.go#L46-L51

As you add a new field, you need to use `utilconversion` to save the field when round-tripping to older API versions. See how it is done in these diffs from #1247:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1247/files#diff-9a53c6afb893cfd6bb4f50185dea035075cb0ef25fce713667c270d5c9668a31R39-R47

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1247/files#diff-9a53c6afb893cfd6bb4f50185dea035075cb0ef25fce713667c270d5c9668a31R59-R62

**Comment by jichenjc** [comment]
@mkjpryor maybe you can refer to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1323
At least I can pass all the test :)

**Comment by mkjpryor** [comment]
@jichenjc @apricote @mdbooth 

Finally got the tests passing 🎉

**Comment by mkjpryor** [comment]
@apricote @mdbooth @tobiasgiese Anything else before this is good to go?

**Comment by tobiasgiese** [comment]
> @apricote @mdbooth @tobiasgiese Anything else before this is good to go?

I‘ll take a look tomorrow :)

**Comment by tobiasgiese** [comment]
/lgtm

Let's wait for an answer of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1252#issuecomment-1246313295. @jichenjc can approve afterwards

**Pull request merged**
