### PR TITLE
Remove unnecessary instanceStatus.State() call

### PR DESCRIPTION
**Pull request by Bo0km4n**
**What this PR does / why we need it**:
To remove unnecessary instanceStatus.State() call

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by tobiasgiese** [comment]
I don't think that this change is needed nor correct.

We're just using the variable `state` as a pointer helper for `openStackMachine.Status.InstanceState`.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6ba04de45920c102886bdeeeb21bf1a1119c5967/controllers/openstackmachine_controller.go#L330-L331

Further, calling `instanceStatus.State()` just returns the string of the instance state.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6ba04de45920c102886bdeeeb21bf1a1119c5967/pkg/cloud/services/compute/instance_types.go#L91-L93

**Comment by mdbooth** [comment]
It's a toss up, tbh. However, I think pulling state into a variable is less frequent than just calling it, so on balance I'm inclined to say calling State() is more idiomatic. I don't think either is 'wrong', though.

However, note that State() is *extremely* cheap. In fact godbolt suggests there's a good chance (compiler optimisations permitting) it's free here: https://godbolt.org/z/PbYE68Wof (note how neither switch statement generates code).

There may be an improvement we could make here, though. I said that we don't normally pull State() into a variable, and we wouldn't have to do it here if we did:

```golang
openStackMachine.Status.InstanceState = pointer.String(instanceStatus.State())
```

Is that easier on the eye? I don't think there's much in it.

What brought you to the code today, btw?

**Comment by Bo0km4n** [comment]
I apprecieate your reviews.
If you guys don't think it's necessary, it doesn't have to be merged.
The reason I submitted this PR this time is simply because I thought it was a useless code.
I was not thinking of any compiler-level optimizations.

**Comment by tobiasgiese** [comment]
I'll close this PR.
@Bo0km4n if you want to re-discuss this topic, feel free to reopen it 🙂

**Pull request closed without merging**
