### PR TITLE
🌱 Reduce cyclomatic complexity of reconcileNetworkComponents

### PR DESCRIPTION
**Pull request by mdbooth**
This change refactors reconcileNetworkComponents into several smaller logical functions which are easier to read and reason about.

It also makes the gocyclo linter happy when making new changes to this code.

/hold

### CODE REVIEW

**Comment by EmilienM** [comment]
@mdbooth I've added little tests to it, but I think we need to:
* Split `controllers/openstackcluster_controller.go` into multiple files handling resources in different files and one file for the higher level loops. We shouldn't do that in this PR and I volunteer to do it when I'm back. I've tracked this in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1907.
* Write more tests regarding the network & subnet resources, this is out of scope for this PR so I'm inclined to postpone it (I created https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1908) - I wonder if @MaysaMacedo can help when time permits.

**Comment by mdbooth** [comment]
Lazily hoping that was a flake without checking:

/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
Testing if our jobs now work in the community prow cluster
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by mdbooth** [comment]
Looks like something related to floating IPs is borked because we run out. Perhaps they're not being deleted, or created in a loop. It's hard to tell, though, because of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1840

**Comment by mdbooth** [comment]
I think I found the problem from code inspection, although this PR also currently includes #1913 for improved logging just in case. The issue was that we were re-executing floating IP creation on every cluster reconcile when not using an Octavia loadbalancer.

**Comment by mdbooth** [comment]
Yay! Looks like that fixed it.

**Pull request merged**
