### PR TITLE
✨ Update CAPI to v1beta1

### LINKED ISSUE #1029: Cut a v0.5.0
todos:

- ~~[ ] create new CAPO types (`v1alpha5`)~~
- ~~[ ] create conversion webhooks~~
- [ ] bump capi dependency
- [ ] create release-0.4 branch
- [ ] tag v0.5.0
- [ ] release v0.5.0

From migration docs:

- [ ] bump controller-runtime dependency to v0.10.+
- [ ] bump controller-tools version to v0.7.+
- [ ] check if not already done: Ensure your template resources support `template.meta` fields. Refer to the [cluster](https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure.html) and [machine](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html) provider contract docs for more information. This is not required, but is recommended for consistency across the infrastructure providers as Cluster API graduates and opens up use cases where coordinating controllers can use labels and annotations from template infrastructure resources to do external provisioning or provide configuration information, e.g. [IPAM support for vSphere / bare-metal](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1210).

_Originally posted by @chrischdi in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1024#issuecomment-947523939_

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This PR update CAPI to v1beta1.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1029 

**Special notes for your reviewer**:

To succeed e2e test, we need to use a newer CAPI version in go.mod to pick up this fix: https://github.com/kubernetes-sigs/cluster-api/pull/5526/files#diff-339b1ff9c6f1a0cd32f51981c70dee16dbae406339bb56229f4a910ff3cb5c0bL20.

We followed CAPA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2897

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

/hold

### CODE REVIEW

**Comment by hidekazuna** [comment]
@sbueringer @jichenjc PTAL

**Review by tobiasgiese — COMMENTED** [review]
/lgtm
👍🏻 nice one
But we should create a 0.4.1 release for this change, right? Maybe I missed a discussion about this topic.

**Comment by jichenjc** [comment]
@tobiasgiese some discussion here 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1024

I also agree a 0.4.1 seems reasonable to me

**Comment by tobiasgiese** [comment]
> @tobiasgiese some discussion here #1024

Thanks @jichenjc. I followed that issue already, but found nothing about a build release (i.e. v0.4.1).
But tbh, a v0.5.0 would feel more right to me with the change to CAPI v1beta1. I just wanted to persist it somewhere, that we should release *at least* a v0.4.1. WDYT?

**Comment by jichenjc** [comment]
==> v0.4.1 (based on v1alpha4 CAPI), with CAPO v1alpha4  (so that we can maintain those features and backport)
  ||
  ==> v0.5.0 (based on v1beta1 CAPI) ,  with CAPO v1alpha5 (potentially?)

I guess this is what we want?

**Comment by tobiasgiese** [comment]
> ==> v0.4.1 (based on v1alpha4 CAPI), with CAPO v1alpha4 (we can backport if want) || ==> v0.5.0 (based on v1beta1 CAPI) , with CAPO v1alpha5 (potentially?)
> 
> I guess this is what we want?

But in this case we should create a `release-0.4` branch before merging this PR

**Comment by jichenjc** [comment]
>>But in this case we should create a release-0.4 branch before merging this PR

yes, I think it's normal way we do such kind of update work?

**Comment by hidekazuna** [comment]
@jichenjc @tobiasgiese My idea is that:
This PR is for minor release since API has been changed. Of course we need to create release-0.4 before merge this PR.
After merging this PR and release v0.5.0, we create v1beta1 API and start developing v1.0.0 with v1beta1.

This idea follows CAPA. CAPA releases v0.5 and v0.6 with v1alpha3. After that release v0.7 with v1alpha4 then v1.0 with v1beta1(https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/metadata.yaml). Currently they seems maintain v0.6 with v1alpha3, v0.7 with v1alpha4, and v1.0 with v1beta1.

**Comment by jichenjc** [comment]
>>>The point is that they released two minor versions with the same API version.

ok, that make sense , thanks for the summary~

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by jichenjc** [comment]
let's keep this open for a few dates to gain more insight 
we might merge it later this week if no objection..

**Pull request merged**
