### PR TITLE
Fix shabang of generate-yaml.sh

### LINKED ISSUE #81: generate-yaml.sh failed with "./generate-yaml.sh: 100: read: Illegal option -s"
generate-yaml.sh failed with "./generate-yaml.sh: 100: read: Illegal option -s" on Ubuntu.
Bacause Ubuntu default shell is dash which does not support read with -s option.

Shebang of generate-yaml.sh should be /bin/bash instead of /bin/sh.

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This patch updates shebang from /bin/sh to /bin/bash of generate-yaml.sh

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #81

### CODE REVIEW

**Comment by hidekazuna** [comment]
I signed it

**Comment by m1093782566** [comment]
/lgtm

THANKS!

**Comment by flaper87** [comment]
Thanks for the patch! :cake:

**Pull request merged**
