### PR TITLE
🐛 Fix enabling of disabled bastion on upgrade to v1beta1

### LINKED ISSUE #2050: In Cluster conversion bug from v1alpha7 to v1beta1
/kind bug

**What steps did you take and what happened:**
After updating the capo controller to v0.10.1, all existing openstackcluster have the bastion host enabled, also all where disabled before.

**What did you expect to happen:**
No change in bastion host state

**Anything else you would like to add:**
We are using cluster class.

That was the OpenStackClusterTemplate that was applied while the cluster was still capo v0.9.0

      ---
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
      kind: OpenStackClusterTemplate
      metadata:
        name: test2
        namespace: gks-cdc1061c
      spec:
        template:
          spec:
            tags:
              - GKSv3
              - clustertype=manifest
              - clusterid=cdc1061c
              - customerid=xxxxx
            apiServerLoadBalancer:
              enabled: true
            bastion:
              enabled: false <----
            cloudName: openstack
            externalNetworkId: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              kind: Secret
              name: test2-cloud-config
            managedSecurityGroups: true
            allowAllInClusterTraffic: true
            nodeCidr: 192.168.1.0/24

After upate we have:

      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      metadata:
        annotations:
          cluster.x-k8s.io/conversion-data: '{"spec":{"h":"paezU1TJYTA=","d":{"template":{"spec":{"cloudName":"openstack","nodeCidr":"192.168.1.0/24","network":{},"subnet":{},"externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","apiServerLoadBalancer":{"enabled":true},"disableAPIServerFloatingIP":false,"managedSecurityGroups":true,"allowAllInClusterTraffic":true,"tags":["GKSv3","clustertype=manifest","clusterid=cdc1061c","customerid=xxx"],"controlPlaneEndpoint":{"host":"","port":0},"bastion":{"enabled":false,"instance":{"cloudName":"","flavor":""}},"identityRef":{"kind":"Secret","name":"test2-cloud-config"}}}}}}'
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha7","kind":"OpenStackClusterTemplate","metadata":{"annotations":{},"name":"test2","namespace":"gks-cdc1061c"},"spec":{"template":{"spec":{"allowAllInClusterTraffic":true,"apiServerLoadBalancer":{"enabled":true},"bastion":{"enabled":false},"cloudName":"openstack","externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","identityRef":{"kind":"Secret","name":"test2-cloud-config"},"managedSecurityGroups":true,"nodeCidr":"192.168.1.0/24","tags":["GKSv3","clustertype=manifest","clusterid=cdc1061c","customerid=xxx"]}}}}
        creationTimestamp: "2024-04-11T11:33:12Z"
        generation: 1
        name: test2
        namespace: gks-cdc1061c
        ownerReferences:
        - apiVersion: cluster.x-k8s.io/v1beta1
          kind: ClusterClass
          name: cluster-class-test2
          uid: 42f97373-c6b2-41fe-8231-13aa55e41f76
        resourceVersion: "61008076"
        uid: 9a85caf3-a7da-412e-a881-0d492872d177
      spec:
        template:
          spec:
            apiServerLoadBalancer:
              enabled: true
            bastion: {} <-----
            externalNetwork:
              id: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              cloudName: openstack
              name: test2-cloud-config
            managedSecurityGroups:
              allowAllInClusterTraffic: true
            managedSubnets:
            - cidr: 192.168.1.0/24
            tags:
            - GKSv3
            - clustertype=manifest
            - clusterid=cdc1061c
            - customerid=xxx

And we have a error message in the ClusterObject:
`error reconciling the Cluster topology: failed to create patch helper for OpenStackCluster/test2-6jn42: server side apply dry-run failed for original object: OpenStackCluster.infrastructure.cluster.x-k8s.io "test2-6jn42" is invalid: spec.bastion: Invalid value: "object": spec is required if bastion is enabled`

Which make sense as we never wanted a bastion host

If more resources are need i can try to provide!

For newly applied resources, the behavior seems a little bit different.  For old one `bastion: {}` is in indirect enabled true

Wen I create a new cluster:

      ---
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
      kind: OpenStackClusterTemplate
      metadata:
        name: test-conversion
        namespace: gks-c34f002a
      spec:
        template:
          spec:
            tags:
              - GKSv3
              - clustertype=manifest
              - clusterid=c34f002a
              - customerid=xxx
            apiServerLoadBalancer:
              enabled: true
            bastion:
              enabled: false <----
            cloudName: openstack
            externalNetworkId: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              kind: Secret
              name: test-conversion-cloud-config
            managedSecurityGroups: true
            allowAllInClusterTraffic: true
            nodeCidr: 192.168.1.0/24

If see it explicitly enabled:

      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      metadata:
        annotations:
          cluster.x-k8s.io/conversion-data: '{"spec":{"h":"fKff97WHSbw=","d":{"template":{"spec":{"cloudName":"openstack","nodeCidr":"192.168.1.0/24","network":{},"subnet":{},"externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","apiServerLoadBalancer":{"enabled":true},"disableAPIServerFloatingIP":false,"managedSecurityGroups":true,"allowAllInClusterTraffic":true,"tags":["GKSv3","clustertype=manifest","clusterid=c34f002a","customerid=C00106"],"controlPlaneEndpoint":{"host":"","port":0},"bastion":{"enabled":false,"instance":{"cloudName":"","flavor":""}},"identityRef":{"kind":"Secret","name":"test-conversion-cloud-config"}}}}}}'
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha7","kind":"OpenStackClusterTemplate","metadata":{"annotations":{},"name":"test-conversion","namespace":"gks-c34f002a"},"spec":{"template":{"spec":{"allowAllInClusterTraffic":true,"apiServerLoadBalancer":{"enabled":true},"bastion":{"enabled":false},"cloudName":"openstack","externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","identityRef":{"kind":"Secret","name":"test-conversion-cloud-config"},"managedSecurityGroups":true,"nodeCidr":"192.168.1.0/24","tags":["GKSv3","clustertype=manifest","clusterid=c34f002a","customerid=C00106"]}}}}
        creationTimestamp: "2024-05-03T05:47:40Z"
        generation: 1
        name: test-conversion
        namespace: gks-c34f002a
        resourceVersion: "81074279"
        uid: b57212f6-a432-498a-8289-79fb1afd4c72
      spec:
        template:
          spec:
            apiServerLoadBalancer:
              enabled: true
            bastion:
              enabled: true    <-----
            externalNetwork:
              id: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              cloudName: openstack
              name: test-conversion-cloud-config
            managedSecurityGroups:
              allowAllInClusterTraffic: true
            managedSubnets:
            - cidr: 192.168.1.0/24
            tags:
            - GKSv3
            - clustertype=manifest
            - clusterid=c34f002a
            - customerid=C00106

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.10.1
- Cluster-API version: v1.6.3
- OpenStack version: Yoga
- Minikube/KIND version: xxx
- Kubernetes version (use `kubectl version`): v1.29.2
- OS (e.g. from `/etc/os-release`): flatcar

### PR DESCRIPTION
**Pull request by mdbooth**
Fixes #2050

/hold

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by mdbooth** [comment]
Leaving the hold until full-test passes.

**Pull request merged**
