### PR TITLE
🐛 Ignore 'OS_*' environment variables

### PR DESCRIPTION
**Pull request by stephenfin**
**What this PR does / why we need it**:

Ignore `OS_` prefixed environment variables when building our clients.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #1991

**Special notes for your reviewer**:

None.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
We had the same issue in OpenShift that we [fixed in the same way](https://github.com/openshift/installer/blob/05453ef/pkg/types/openstack/defaults/clientopts.go#L11-L14).

/lgtm

**Review by mdbooth — APPROVED** [review]

**Pull request merged**
