### PR TITLE
🏃 Update golangci-lint and fix most of the linter issues

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

After the v1alpha4 update I had to pin golangci-lint because there were just too many findings
and I didn't want to also fix them in the same PR. This PR now fixes all findings except some 
complexity findings (nestif & cyclop). Those can be fixed in other follow-up PRs.

Notes:
* this PR can also be reviewed but won't be merged before the test framework PR and also contains the test framework commit/PR

- [x] squashed commits
- if necessary:
  - [x] includes documentation
  - [x] adds unit tests

/hold

### CODE REVIEW

**Comment by sbueringer** [comment]
@jichenjc @hidekazuna @prankul88 Pull request can be reviewed now, please take a look :)

**Comment by jichenjc** [comment]
you have 2 commits
```
 implement conformance test with e2e framework
@sbueringer
sbueringer committed 4 days ago

update linter and fix some issues 
```

should I merge this one first?

**Comment by sbueringer** [comment]
> you have 2 commits
> 
> ```
>  implement conformance test with e2e framework
> @sbueringer
> sbueringer committed 4 days ago
> 
> update linter and fix some issues 
> ```
> 
> should I merge this one first? @sbueringer

In this order:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/782
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/797
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798

I'll drop the duplicate commit after the #782 is merged here. Just wanted to build on top and test the combination of this stuff.

**Comment by sbueringer** [comment]
/test pull-cluster-api-provider-openstack-make-conformance

I dropped the commit now. So this could be merged after lgtm :)

**Comment by sbueringer** [comment]
@jichenjc @hidekazuna @prankul88 PTAL, if you have some time :)

**Pull request merged**
