### PR TITLE
Use the kubernetesversions package of the cluster-api repo again

### PR DESCRIPTION
**Pull request by sbueringer**
Test for: https://github.com/kubernetes-sigs/cluster-api/pull/4420

/hold

### CODE REVIEW

**Comment by sbueringer** [comment]
/cc @hidekazuna @jichenjc @seanschneeweiss @chrischdi 

As my [PR in cluster-api](https://github.com/kubernetes-sigs/cluster-api/pull/4420) has been merged let's drop our fork of the package.

**Review by chrischdi — COMMENTED** [review]
Looks straight Forward

/lgtm

**Comment by hidekazuna** [comment]
Great.

/unfold

**Comment by sbueringer** [comment]
/test pull-cluster-api-provider-openstack-e2e-test

(testing again after the sshuttle fix)

**Comment by sbueringer** [comment]
This commit already had a green test run so I assume it's just the flake and keep retrying
/retest

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/k8s.io/issues/2318

**Pull request merged**
