### PR TITLE
WIP CI: Wait more for the kubeconfig to be available

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

Wait 300s to 600s for the kubeconfig to become available in CI test.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
let's try this

**Comment by hidekazuna** [comment]
recheck

**Comment by hidekazuna** [comment]
Getting secret succeeds within 300s.

**Pull request closed without merging**
