### PR TITLE
🐛 Update reference to the latest version of CAPO v0.3.1

### LINKED ISSUE #651: Reference latest version of CAPO in Makefile
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/Makefile#L319
`make create-cluster` command refer to old CAPO version.

**What did you expect to happen:**
This should be changed to v0.3.1

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by prankul88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #651 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by prankul88** [comment]
recheck

**Comment by jichenjc** [comment]
/lgtm 

thanks

**Pull request merged**
