### PR TITLE
⚠️  remove unused v1alpha2 package and update doc

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

As we're not really (imho) supporting migrations from v1alpha2 to v1alpha3 and the v1alpha2 package was unused in our implementation I would suggest removing it. I'm happy when we have v1alpha3 finalized I don't think we have the bandwidth to support migrations explicitly right now

See also: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/499

### CODE REVIEW

**Comment by hidekazuna** [comment]
@sbueringer I agree we remove v1alpha2, I am not sure Cluster API policy though.
This PR seems conflict with #516 which drops v1alpha2 partially.

**Comment by sbueringer** [comment]
> @sbueringer I agree we remove v1alpha2, I am not sure Cluster API policy though.
> This PR seems conflict with #516 which drops v1alpha2 partially.

Shouldn't conflict. The goal of the other one was mainly to fix the makefile so our images after merge on master are build again, because that's broken for a while now. It's just that the regeneration with the new makefile removed a lot of v1alpha2 occurences.

Afaik there is no official policy. Or at least it doesn't make sense to keep orphaned packages when we're not using them

**Comment by sbueringer** [comment]
I'll close this PR here and use just the other one to make it not even more complicated. Sorry :/

**Pull request closed without merging**
