### PR TITLE
🌱 Use k8s v1.28 in tests

### PR DESCRIPTION
**Pull request by lentzi90**
Bump Kubernetes to v1.28.2 for e2e tests and bump envtest Kubernetes
version to v1.28.0. Also removes the now unused USE_CI_ARTIFACTS
environment variable that was set in some places.

### CODE REVIEW

**Comment by lentzi90** [comment]
I cannot find the issue. Rerunning to rule out flake...
/test pull-cluster-api-provider-openstack-e2e-full-test

**Comment by lentzi90** [comment]
:facepalm: triggered wrong test...
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
@tormath1 could there be something wrong with the flatcar image? I created it with image-builder in the same way as I did the ubuntu image. Any special settings needed?
I'm a bit lost on why it fails, but it has failed 2 times in the flatcar test. I will debug more myself also a bit later

**Comment by lentzi90** [comment]
Thanks @tormath1 ! I have built a new image and uploaded. Let's see how it goes! :crossed_fingers: 
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
Fantastic! It worked! :slightly_smiling_face: Thanks again for the help!

**Comment by lentzi90** [comment]
Updated the table in the readme. I just added v1.28 to it and did not remove any of the older versions or check marks. My reasoning is that we have, for example, tested CAPO v1alpha6 with k8s v1.23 at some point so the check mark is still valid, even though we do not currently test it.

**Comment by jichenjc** [comment]
>>> did not remove any of the older versions or check marks. My reasoning is that we have, for example, tested CAPO v1alpha6 with k8s v1.23 at some point so the check mark is still valid, even though we do not currently test it.

**Comment by jichenjc** [comment]
>>> did not remove any of the older versions or check marks. My reasoning is that we have, for example, tested CAPO v1alpha6 with k8s v1.23 at some point so the check mark is still valid, even though we do not currently test it.

we can achieve those `older` version at some point later and keep newer enough info

**Pull request merged**
