### PR TITLE
✨ Bump CAPI to v1.8.4

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

The latest stable version on October 31th 2024.

### CODE REVIEW

**Review by mdbooth — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by EmilienM** [comment]
oh it didn't finish the execution of the e2e jobs because they are optional :confused: 
we should change the job layout to make the regular e2e job required, IMO.

**Pull request merged**
