### PR TITLE
Update e2e test and document of non lb case

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

Following up #573 , update e2e test and document for non lb case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This PR updates templates/cluster-template-without-lb.yaml.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
reasonable change.. let's wait for test result

**Comment by jichenjc** [comment]
@hidekazuna looks like the error is reasonable 
so need further check on what really happened
`2020-08-05 06:10:58.521291 | ubuntu-bionic-large | !!! Error in ./hack/ginkgo-e2e.sh:153`

**Comment by hidekazuna** [comment]
Calico does not work properly.
https://logs.openlabtesting.org/logs/08/608/935568bfd165048615fa151079f7f2860a5c0500/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/51da6aa/logs/_artifacts/logs/capi-quickstart-control-plane-xhnpg/containers/calico-node-4qcvq_kube-system_calico-node-36df48115bc1a2d0d81466c873b3eb44e9f83c306b41a9a1dcf9d440a48fe1d5.log

```
2020-08-05T06:06:52.628796424Z stdout F 2020-08-05 06:06:51.799 [INFO][102] felix/endpoint_mgr.go 450: Re-evaluated workload endpoint status adminUp=true failed=false known=true operUp=false status="down" workloadEndpointID=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"kube-system/calico-kube-controllers-578894d4cd-6gj9v", EndpointId:"eth0"}
2020-08-05T06:06:52.628974252Z stdout F 2020-08-05 06:06:51.801 [INFO][102] felix/status_combiner.go 58: Storing endpoint status update ipVersion=0x4 status="down" workload=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"kube-system/calico-kube-controllers-578894d4cd-6gj9v", EndpointId:"eth0"}
2020-08-05T06:06:52.748041188Z stdout F 2020-08-05 06:06:51.832 [INFO][102] felix/wireguard.go 578: Wireguard is not enabled
2020-08-05T06:06:52.748066909Z stdout F 2020-08-05 06:06:51.896 [INFO][102] felix/status_combiner.go 78: Endpoint down for at least one IP version id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"kube-system/calico-kube-controllers-578894d4cd-6gj9v", EndpointId:"eth0"} ipVersion=0x4 status="down"
2020-08-05T06:06:52.748080052Z stdout F 2020-08-05 06:06:51.903 [INFO][102] felix/status_combiner.go 98: Reporting combined status. id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"kube-system/calico-kube-controllers-578894d4cd-6gj9v", EndpointId:"eth0"} status="down"
```

This may be fixed by https://github.com/projectcalico/cni-plugin/pull/895.

**Comment by hidekazuna** [comment]
recheck

**Comment by hidekazuna** [comment]
@jichenjc check status: success. we can merge now.

**Pull request merged**
