### PR TITLE
:seedling: bump docker distribution to 2.8.2+incompatible

### PR DESCRIPTION
**Pull request by tuminoid**
Bump docker/distribution to 2.8.2+incompatible for https://osv.dev/vulnerability/GHSA-hqxw-f8mx-cpmw

### CODE REVIEW

**Comment by tobiasgiese** [comment]
Please rebase first :)
There are several commits that are already on the `main` branch

**Comment by tuminoid** [comment]
> Please rebase first :) There are several commits that are already on the `main` branch

Done. Sorry for that, pushing stuff you've left alone for a minute fall behind so fast :)

**Comment by tobiasgiese** [comment]
/ok-to-test
/lgtm
/approve

Thanks for bumping this! :)

**Pull request merged**
