### PR TITLE
📖 Upgrading a cluster without LBaaS is not supported

### LINKED ISSUE #912: Upgrading clusters without Octavia
/kind bug

**What steps did you take and what happened:**

I've tried upgrading k8s using the following command:

```
kubectl patch kubeadmcontrolplane control-plane --type=json \
  -p '[{"op": "replace", "path": "/spec/version", "value": "1.18.12"}]'
```

We didn't have Octavia installed, so what happened was that the floating IP moved to the new instance, which was trying to join the existing cluster using the floating ip that had already been moved.

**What did you expect to happen:**

I was expecting the k8s upgrade operation to complete successfully.

**Anything else you would like to add:**

I'm not sure if this can be considered a bug or just an undocumented limitation. Is there a way in which we could get the cluster upgrade operation to work without having Octavia (Neutron LBaaS)? One possible approach would be to use the private IPs instead of the floating IP as part of the upgrade workflow.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.4
- Cluster-API version: v0.3.16
- OpenStack version: Victoria
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

Upgrading a cluster without LBaaS is not supported.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #912 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by hidekazuna** [comment]
@jichenjc PTAL

**Comment by jichenjc** [comment]
@hidekazuna can we open an issue to track this feature? thanks

/lgtm
/hold cancel

**Pull request merged**
