### PR TITLE
fix template after change securityGroups from string to SecurityGroupParam

### LINKED ISSUE #265: fix template after change securityGroups from string to SecurityGroupParam
In ticket https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/236, `securityGroups` are changed in API but not template.

`cmd/clusterctl/examples/openstack/machines.yaml.template`
```
         securityGroups:
           - <Security Group ID>
```

It should be `- uuid : <Security Group ID>`

### PR DESCRIPTION
**Pull request by xunpan**
SecurityGroupParam

**What this PR does / why we need it**:
 Default template is not correct after changes of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/236

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #265

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

cc @iamemilio

### CODE REVIEW

**Comment by jichenjc** [comment]
error getting kubeconfig: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field OpenstackProviderSpec.securityGroups of type string


I still get this error with the change here...

**Comment by flaper87** [comment]
@iamemilio can you review this?

**Comment by ainmosni** [comment]
/lgtm

I used this syntax a lot while testing the container linux support.

**Comment by hidekazuna** [comment]
This fixing works in my environment.

**Pull request merged**
