### PR TITLE
🐛 Don't log nil error when AuthInfo is not set

### PR DESCRIPTION
**Pull request by mdbooth**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This change is trivial. It does $SUBJECT.

**TODOs**:

- [] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
Eurgh, I really ought to do the paperwork to join the sig.

**Comment by hidekazuna** [comment]
Could you add PR comment and commit message?

**Comment by mdbooth** [comment]
> 
> 
> Could you add PR comment and commit message?

It's trivial. I couldn't really say more than $SUBJECT.

**Pull request merged**
