### PR TITLE
🐛  no more reconcileExternalnetwork when not use external network

### LINKED ISSUE #1490: No need to ReconcileExternalNetwork when disableApiserverFloatingIP and NodeCIDR is empty string
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In openstackcluster_controller，when disableApiserverFloatingIP, will not use external network to create a floatingIP;when NodeCIDR is empty string, there is no need to reconcile network and create router between external network and subnet; 

**What did you expect to happen:**
when disableApiserverFloatingIP and the NodeCIDR is empty string, it won't excute the  ReconcileExternalNetwork

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:1.1.4
- OpenStack version:0.6.3
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by ruifaling**
NodeCIDR is empty string

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1490 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by ruifaling** [comment]
please have a review,thanks ! @jichenjc  @mdbooth @tobiasgiese

**Comment by tobiasgiese** [comment]
/approve cancel

please squash your commits first

**Comment by mdbooth** [comment]
@ruifaling Are you able to update?

**Comment by ruifaling** [comment]
@mdbooth  Sorry for the late reply. My original email was closed, and I just got my account back. I'll come back to this later

**Pull request closed without merging**
