### PR TITLE
Enabled kubeadm debug log for better troubleshooting.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Enabled debug log for kubeadm post install.
```

### CODE REVIEW

**Comment by xunpan** [comment]
/lgtm
It is example code and already set `-x` for shell. I think add this detailed log helps in trying the case.

**Comment by gyliu513** [comment]
This can  also help me to debug the issue like https://github.com/kubernetes/kubeadm/issues/1474

**Comment by jichenjc** [comment]
I think a better way is to provide a configuration option such as 'debug' so that we can use in clusterctl to pass the flag for whole debug purpose, I will open an issue in cluster-api

**Comment by jichenjc** [comment]
ok, already a '-v' flag in clusterctl and seems this is another good example to discuss along with 
https://github.com/kubernetes-sigs/cluster-api/issues/866

a common configuration for those settings seems reasonable

**Pull request merged**
