### PR TITLE
check InfrastructureRef  before usage

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

potential fix for #1372 ,from the call stack looks like the infrastructureRef might be nil
and lead to that issue, do no harm if we add such check ..

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Review by mdbooth — COMMENTED** [review]
This fixes the panic, but it's just a line in the controller logs so it doesn't let the user know what they need to fix. This needs to be user-visible somehow.

How does the InfrastructureRef get set? It's in the spec so I'd *hope* it's by the user, at least indirectly, but that's not always the case. If it's by the user, why would it not be set? Could we catch this in the cluster controller instead and set an appropriate condition there?

**Comment by jichenjc** [comment]
@mdbooth based on https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html
the Spec.InfrastructureRef is set by CAPI, I am wondering whether it's a timing issue
so with proposed logic, we will enter `OpenStackCluster is not ready yet` logic then we will retry which seems fit for 
fixing timing issue

**Review by seanschneeweiss — COMMENTED** [review]
CAPD seems to have a different approach.
They filter the watch to only add dockermachines to the list that reference machines with having set the infrastructureRef.

See https://github.com/kubernetes-sigs/cluster-api/blob/5bc3b40be412f22e86d0ad6297f5f9764e33324b/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L436-L439
and
https://github.com/kubernetes-sigs/cluster-api/blob/5bc3b40be412f22e86d0ad6297f5f9764e33324b/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L476-L478

What do you think of doing something similar to that?

**Comment by mdbooth** [comment]
@jichenjc Shall we reopen this? I doubt we've fixed it any other way since.

**Comment by jichenjc** [comment]
/reopen 

will see whether I can find sometime to continue to work on this soon..

**Pull request closed without merging**
