### PR TITLE
✨ Add gophercloud request logs, fix contexts

### LINKED ISSUE #854: Make it possible to enable gophercloud request logs via --v
/kind feature

**Describe the solution you'd like**
Similar to the ccm it would be great if with `--v=6` the gophercloud client would log it's requests. This would really help during debugging

**Anything else you would like to add:**
We already have this implemented downstream. So we would open a PR to cherry-pick this upstream.

### PR DESCRIPTION
**Pull request by seanschneeweiss**
**What this PR does / why we need it**:
This PR enables the gophercloud request logs when setting the log level to `6` with `--v=6`.

In addition, some contexts are fixed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #854. 

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- if necessary:
  - ~~[ ] includes documentation~~
  - ~~[ ] adds unit tests~~

/hold

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Review by sbueringer — APPROVED** [review]

**Comment by sbueringer** [comment]
@jichenjc @seanschneeweiss  this needs a gofmt

**Comment by hidekazuna** [comment]
/lgtm

I tested in my environment. So great.

**Comment by jichenjc** [comment]
/approve

looks good

**Pull request merged**
