### PR TITLE
✨ Add Tags to API-Loadbalancer resources

### LINKED ISSUE #1455: Add tags to loadbalancer resources too
/kind feature

**Describe the solution you'd like**
With v1alpha6 tags where added to nearly all openstack resources, but not to the loadbalancer, pools, listeners and members . 
I would like to have them there too.

Any special reason why this is missing?

### PR DESCRIPTION
**Pull request by qeqar**
**What this PR does / why we need it**:

Add Tags to loadbalancer struct
Add Tags to the
- loadbalancer
- pool
- listener
- member

NOT for the Monitor object, Openstack supports Tags, but the Gohpercloud is not (looked also into newest released version v1.1.1)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1455

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by qeqar** [comment]
Ok, wanted to push early!

And get some feedback:
I cannot find any test that tests the api loadbalancer explicitly. Did i miss it, or are there any testcases i can extent for the new tag feature.

Monitors supporting tags, but gophercloud not see here:https://pkg.go.dev/github.com/gophercloud/gophercloud@v1.1.1/openstack/loadbalancer/v2/monitors#CreateOpts

Is their a need to make a feature request to them too?


Now i need to get my local dev stack ready to at least see if it works :-)


cc: @mdbooth

**Review by lentzi90 — COMMENTED** [review]
The code looks fine to me. Do I understand correctly that the point of this is to set the same tags that are specified in `openstackcluster.spec.tags` on the loadbalancer objects?

Edit: Please squash the commits when you feel ready

**Comment by qeqar** [comment]
OK squashed and updated the PR.

and yes wanted to add the same Tags as openstackcluster.
They are already used in all other resources.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

I will trigger the e2e-full test since this is changing the API and that could affect `clusterctl upgrade`.

/test pull-cluster-api-provider-openstack-e2e-full-test

**Comment by jichenjc** [comment]
/approve

still hold for folks to take a quick look

**Comment by jichenjc** [comment]
/hold cancel

no other comments, assume good to go :)

**Pull request merged**
