### PR TITLE
Add ability to authenticate with CA certificate

### PR DESCRIPTION
**Pull request by cdc1807**
```release-note
Add ability to authenticate with CA certificate
```

### CODE REVIEW

**Comment by hidekazuna** [comment]
@cdc1807 Is this PR for implementing #209 ? I am afraid I proposed #224 separately without seeing this PR. 
Your PR is lack of cinsidering cacert is a file path, not certificate itself. Also we have to care about cloud.conf which needs for openstack cloud provider.

**Comment by cdc1807** [comment]
@hidekazuna When I originally wrote the code there was no issue opened for this.  My fault for not checking before submitting.  But I intentionally coded it so that there is no file to read from.  To me it's simpler as an end user, all provider authentication is still in 1 place.  Not to mention one less secret to keep up with.  An additional change I could make is to `generate.yaml` to read a user given file and inject it.

Example of how it looks:
```
clouds:
  openstack:
    auth:
      username: username
      password: password
      user_domain_name: domain
      project_id: project_id
      auth_url: auth_url
    interface: public
    identity_api_version: 3
    region_name: region_name
    verify: False
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIEczCCA1ugAwIBAgIBADANBgkqhkiG9w0BAQQFADAkGA1UEBhMCR0Ix
      EzARBgNVBAgTClNvbWUtU3RhdGUxFDASBgNVBAoTC00EgTHRkMTcwNQYD
      VQQLEy5DbGFzcyAxIFB1YmxpYyBQcmltYXJ5IENlcnXRpb24gQXV0aG9y
      aXR5MRQwEgYDVQQDEwtCZXN0IENBIEx0ZDAeFw0wMDTUwMTZaFw0wMTAy
      MDQxOTUwMTZaMIGHMQswCQYDVQQGEwJHQjETMBEGA129tZS1TdGF0ZTEU
      MBIGA1UEChMLQmVzdCBDQSBMdGQxNzA1BgNVBAsTLkDEgUHVibGljIFBy
      aW1hcnkgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFDAMTC0Jlc3QgQ0Eg
      THRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgTz2mr7SZiAMfQyu
      vBjM9OiJjRazXBZ1BjP5CE/Wm/Rr500PRK+Lh9x5eJ/ANBE0sTK0ZsDGM
      ak2m1g7oruI3dY3VHqIxFTz0Ta1d+NAjwnLe4nOb7/k05ShhBrJGBKKxb
      8n104o/5p8HAsZPdzbFMIyNjJzBM2o5y5A13wiLitEfyYkQzaxCw0Awzl
      kVHiIyCuaF4wj571pSzkv6sv+4IDMbT/XpCo8L6wTash+etLD6FtTjYbb
      rvZ8RQM1tlKdoMHg2qxraAV++HNBYmNWs0duEdjUbJXI9TtnS4o1Ckj7P
      OfljiQIDAQABo4HnMIHkMB0GA1UdDgQWBBQ8urMCRL5AkIp9NJHJw5TCB
      tAYDVR0jBIGsMIGpgBQ8urMCRLYYMHUKU5AkIp9NJHaSBijCBhzELMAkG
      A1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxFDAoTC0Jlc3QgQ0Eg
      THRkMTcwNQYDVQQLEy5DbGFzcyAxIFB1YmxpYyBQcmENlcnRpZmljYXRp
      b24gQXV0aG9yaXR5MRQwEgYDVQQDEwtCZXN0IENBIEDAMBgNVHRMEBTAD
      AQH/MA0GCSqGSIb3DQEBBAUAA4IBAQC1uYBcsSncwADCsQer772C2ucpX
      xQUE/C0pWWm6gDkwd5D0DSMDJRqV/weoZ4wC6B73f5bLhGYHaXJeSD6Kr
      XcoOwLdSaGmJYslLKZB3ZIDEp0wYTGhgteb6JFiTtnsf2xdrYfPCiIB7g
      BMAV7Gzdc4VspS6ljrAhbiiawdBiQlQmsBeFz9JkF4b3l8BoGN+qMa56Y
      It8una2gY4l2O//on88r5IWJlm1L0oA8e4fR2yrBHXadsGeFKkyNrwGi/
      7vQMfXdGsRrXNGRGnX+vWDZ3/zWI0joDtCkNnqEpVnHoX
      -----END CERTIFICATE-----
```

**Comment by cdc1807** [comment]
My CLA issue should be resolved now, how do I restart the check?

**Comment by hidekazuna** [comment]
@cdc1807 Yeah, CA file content is much simpler and I wish we could use it. But apart from clouds.yaml, OpenStack cloud provider needs `cloud.conf` configuration file which has ca-file key. `cloud.conf` is actually generated in `generate.yaml`: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/cmd/clusterctl/examples/openstack/generate-yaml.sh#L181-L198. 
Even if CA file content is given in clouds.yaml, we have to inject it into kubernetes master components for cloud.conf

**Comment by cdc1807** [comment]
Ok will close

**Comment by hidekazuna** [comment]
@cdc1807 I am glad you are interested in this feature,too. Please help me by reviewing my PR #224 .

**Pull request closed without merging**
