### PR TITLE
🌱 Bump OpenStack and Ubuntu in devstack

### PR DESCRIPTION
**Pull request by mdbooth**
/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
/help

Looks like this actually deployed devstack! Then the e2e tests failed. Haven't looked into that yet.

**Comment by mdbooth** [comment]
> ```
> Oct 10 14:03:57 capo-e2e-controller cloud-init[1721]: The system is finally up, after 825.36 seconds
> ```
> 
> This is phenomenal! 🤯
> 
> Usually we have something like [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-e2e-test-main/1711794891727572992)
> 
> ```
> Oct 10 18:06:25 capo-e2e-controller cloud-init[1735]: The system is finally up, after 2372.42 seconds
> ```

Probably because it's failing to deploy something critical, which results in the tests failing 😆  Still haven't had a chance to get back to this.

**Comment by lentzi90** [comment]
I guess this was replaced by #1804? Can we close it?

**Pull request closed without merging**
