### PR TITLE
change to use v1alpla1.SecurityGroupParam

### PR DESCRIPTION
**Pull request by hchenxa**
**What this PR does / why we need it**:

the type error and without this, the node will create failed due to below issue:
```
E0426 03:09:11.315702       1 controller.go:170] Error checking existence of machine instance for machine object hchenxa1-node-z7xmr; error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field OpenstackProviderSpec.securityGroups of type v1alpha1.SecurityGroupParam
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hchenxa** [comment]
cc @jichenjc @gyliu513

**Comment by jichenjc** [comment]
you have 3 commits, I guess last one is the PR's target？

**Comment by gyliu513** [comment]
@hchenxa we can merge this after you addressed @jichenjc 's comments, only one commit is needed here.

**Comment by hchenxa** [comment]
thanks @jichenjc , will re-create the PR then.

**Pull request closed without merging**
