### PR TITLE
Fix a doc typo

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

FIx a typo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

/hold

### CODE REVIEW

**Review by sbueringer — APPROVED** [review]

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
@hidekazuna @sbueringer this is very small change
please help a lgtm.. thanks

**Pull request merged**
