### PR TITLE
Update kubeadm to 1.15

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
kubectl get nodes --kubeconfig kubeconfigNAME                               STATUS   ROLES    AGE     VERSION
openstack-master-pm4zm.novalocal   Ready    master   4m56s   v1.15.0
openstack-node-qsbnb.novalocal     Ready    <none>   33s     v1.15.0

**Comment by hidekazuna** [comment]
Thanks, I tested this works. Could you update machine-deployment.yaml.template as well?

**Comment by chrigl** [comment]
@jichenjc could you also add 1.15 to the table in README.md

**Comment by sbueringer** [comment]
> kubectl get nodes --kubeconfig kubeconfigNAME STATUS ROLES AGE VERSION
> openstack-master-pm4zm.novalocal Ready master 4m56s v1.15.0
> openstack-node-qsbnb.novalocal Ready 33s v1.15.0

I can also confirm that it just works with Kubernetes & kubeadm 1.15. It also works on my latest multi-node control plane branch.

**Comment by sbueringer** [comment]
@jichenjc Okay so only the change in `machine-deployment.yaml.template` is left until we get this merged?

**Comment by jichenjc** [comment]
I will update the machine-deployment.yaml.template, forgot to update it :)

**Comment by jichenjc** [comment]
@hidekazuna @sbueringer updated the machine-deployment.template

**Comment by sbueringer** [comment]
/lgtm

Thx :)

**Pull request merged**
