### PR TITLE
Add ConfigDrive in zz_generated.deepcopy.go

### LINKED ISSUE #308: Missing ConfigDrive in zz_generated.deepcopy.go
/kind bug

**What steps did you take and what happened:**

When go generate is executed under the pkg/apis directory, ConfigDrive was added to the DeepCopyInto function in zz_generated.deepcopy.go

**What did you expect to happen:**

No update zz_generated.deepcopy.go

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

ConfigDrive was added in #254 

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This PR adds ConfigDrive zz_generated.deepcopy.go by executing go
generate under pkg/apis.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #308 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
That's good fix, but I am curious why this doesn't get generated automatically
can you tell me which command you used to generate this?

**Comment by hidekazuna** [comment]
@jichenjc I executed go generate under pkg/apis. I found this bug when I try to add CloudsSecret to OpenstackClusterProviderSpec.

**Comment by jichenjc** [comment]
you are right, I executed the 'make generate' command and have same changes, this should be when I add this config driver and forgot to run 'make generate'

I think in order to avoid this ,we have 2 choice(may be more),  one is to add guide line (do we have now?) to make sure run generate command before send PR, the other is to add those 
-unit: depend
+unit: depend generate
        go test -tags=unit $(shell go list ./...) $(TESTARGS)
into Makefile so that when doing unit test (most guy will run this) it will be auto generated, 

thoughts? @hidekazuna @chrigl @gyliu513

**Comment by gyliu513** [comment]
Thanks @jichenjc and @hidekazuna I prefer option 2 to update makefile.

```
liugyas-mbp:cluster-api-provider-openstack liugya$ git diff
diff --git a/Makefile b/Makefile
index 9bce4e6a..8cce96ba 100644
--- a/Makefile
+++ b/Makefile
@@ -68,7 +68,7 @@ test: unit functional

 check: depend fmt vet lint

-unit: depend
+unit: generate depend
        go test -tags=unit $(shell go list ./...) $(TESTARGS)

 functional:
@@ -87,7 +87,7 @@ endif
 vet:
        go vet ./...

-cover: depend
+cover: generate depend
        go test -tags=unit $(shell go list ./...) -cover

 docs:
```

This can also make openstack provider keep consistent with other cloud providers, like AWS, Azure etc.

**Comment by jichenjc** [comment]
yes, https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/Makefile#L69 seems has this logic, so @hidekazuna can you help to make changes? Thanks

**Pull request merged**
