### PR TITLE
🌱 dependencies: Bump Go stdlib

### PR DESCRIPTION
**Pull request by pierreprinetti**
**What this PR does / why we need it**:

Upgrade dependencies from the Go standard library, to incorporate bug fixes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by tobiasgiese** [comment]
/ok-to-test

@pierreprinetti we need you to join the @kubernetes-sigs org 🙂 
If you need a sponsor feel free

**Comment by pierreprinetti** [comment]
I suppose I can remove the hold on this one?
/hold cancel

**Pull request merged**
