### PR TITLE
🐛 Invoke KUSTOMIZE in release-manifests

### LINKED ISSUE #568: Kustomize does not get built in MakeFile
/kind bug

**What steps did you take and what happened:**
When I try to run `make release-manifests` I expect the `kustomze` binary to be downloaded. But the command fails with 

> hack/tools/bin/kustomize build config > out/infrastructure-components.yaml
bash: hack/tools/bin/kustomize: No such file or directory
Makefile:315: recipe for target 'release-manifests' failed
make: *** [release-manifests] Error 127

**What did you expect to happen:**
The command should build the binary and execute the command. Requires just a minor fix to `MakeFile` which does not invoke $KUSTOMIZE.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by prankul88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #568 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
> /approval

I think you meant /approve

**Comment by jichenjc** [comment]
/approve

:)

**Pull request merged**
