### PR TITLE
🌱 gce-project.sh: loop over all GCP zones during instance creation

### LINKED ISSUE #1317: Don't rely on a specific GCP zone in our e2e tests
/kind bug

**What steps did you take and what happened:**

Our e2e and conformance tests are failing because of a full GCP zone `us-east4-a`.

**What did you expect to happen:**

**Anything else you would like to add:**

We should adjust our script `hack/ci/gce-project.sh` that we don't have to define a zone.
Maybe there is a way to check if a zone is full or not. If so, we can add several zones and try one after the other until we find a free zone.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by tobiasgiese**
Signed-off-by: Tobias Giese <tobias.giese@mercedes-benz.com>

**What this PR does / why we need it**:

Currently we're facing several "The zone [...] does  not have
enough resources available to fulfill the request" issues.
To hopefully avoid this we have to loop over all zones to create our instance.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1317

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold
/test pull-cluster-api-provider-openstack-conformance-test

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by tobiasgiese** [comment]
First run works 👍🏻 
/hold cancel

**Comment by tobiasgiese** [comment]
/test pull-cluster-api-provider-openstack-conformance-test
/test pull-cluster-api-provider-openstack-e2e-test

And another round 🥳

**Comment by jichenjc** [comment]
/lgtm

seems not that easy to reproduce the original issue but no harm at least :)

**Pull request merged**
