### PR TITLE
🏃 Bump CAPI to v0.3.14

### PR DESCRIPTION
**Pull request by prankul88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

/hold

### CODE REVIEW

**Comment by prankul88** [comment]
retest

**Comment by prankul88** [comment]
`make verify-modules` is working fine in the local setup. Checking dependencies to see where the issue is arising.

**Comment by jichenjc** [comment]
check this https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/767 
@prankul88

**Comment by prankul88** [comment]
@jichenjc Hi, I am curious to know what errors did you get? (with test failure)

**Comment by jichenjc** [comment]
> 
> 
> @jichenjc Hi, I am curious to know what errors did you get? (with test failure)

The pull-cluster-api-provider-openstack-test  failed in my other PR
so I created #767

**Comment by prankul88** [comment]
@jichenjc ohh okay... Lets wait to get that merged first and see. I don't know much about how #767 is fixing it.

**Comment by sbueringer** [comment]
@prankul88 @jichenjc As we decided to wait for the v1alpha4 PR to merge with any further merges. Does it make sense to upgrade to a new v0.3.* version? I'll upgrade to a completely different and newer version. I think this PR probably only makes sense on our `release-0.3` branch.

**Comment by prankul88** [comment]
@sbueringer Got it. So should I close this PR for now or rebase it to the 0.3 branch?

**Comment by sbueringer** [comment]
> @sbueringer Got it. So should I close this PR for now or rebase it to the 0.3 branch?

I think it makes sense to rebase it onto the `release-0.3` branch. I personally don't have a next 0.3 release planned right now. But I assume sooner or later we will have one with this PR and a few other cherry picks.

**Comment by prankul88** [comment]
@sbueringer I rebased the PR to release-0.3 branch, but it automatically added previous commits with it. Can you help me out with this. Thanks

**Comment by sbueringer** [comment]
@prankul88 You essentially only want this commit https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/768/commits/440fb4dc7e6b8a548e367814b599c1e449fde66e right?

From a git perspective there are multiple ways to do this: (those are just two of those :))

1. Rebase your exiting branch (roughly) (I assume upstream is kubernetes-sigs/cluster-api-provider-openstack)
```bash
git fetch upstream
git checkout bump_capi_version
git rebase -i upstream/release-0.3
# then you have to remove all lines except the one with your commit and save the "rebase" file
git push --force
```

2. Re-create the branch: Just create a new branch based on `release-0.3` and cherry-pick the one commit with `git cherry-pick`

**Comment by sbueringer** [comment]
Change looks good. Unfortunately we didn't backport the e2e tests to this branch and they are now mandatory for merge. I'll open a PR which basically runs the conformance tests "as e2e test".

**Comment by prankul88** [comment]
> Change looks good. Unfortunately we didn't backport the e2e tests to this branch and they are now mandatory for merge. I'll open a PR which basically runs the conformance tests "as e2e test".

That would be great. Thanks

**Pull request merged**
