### PR TITLE
fix certificate indentation

### PR DESCRIPTION
**Pull request by jsen-**
**What this PR does / why we need it**:
after #465 the indentation of `cacert` looks something like this:
```
    content: |
                    -----BEGIN CERTIFICATE-----
          MIIFdDCCA1ygAwIBAgIQAThj+/U5lmI7829nD5I++zANBgkqhkiG9w0BAQsFADBU
          ...
```
this PR fixes it

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jsen-** [comment]
CLA signed

**Comment by jichenjc** [comment]
works well in my env

**Pull request merged**
