### PR TITLE
[v1alpha2 Migration] add v1alpha2 types

### PR DESCRIPTION
**Pull request by sbueringer**
This PR is the first step via ClusterAPI v1alpha2. It only creates the new v1alpha2 types in the old kubebuilder structure. See https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/380#issuecomment-522018403 for more details.

This PR doesn't:
* break any v1alpha1 behavior
* touch the machine/cluster actuator
* upgrade to kubebuilder v2

Types have been generated via:
````
kubebuilder create api --group infrastructure --version v1alpha2 --kind OpenStackCluster
kubebuilder create api --group infrastructure --version v1alpha2 --kind OpenStackMachine
````

### CODE REVIEW

**Comment by jichenjc** [comment]
to make it easier for mater
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/447 backport code from master to rlease 0.1 
and 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/448 add hint on relase0.1 branch

so we can start to merge code into master now...

**Comment by sbueringer** [comment]
I'm not sure if I should just close this PR. https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/446 already supersedes it. And I guess its easier to just review the final CRDs.

@jichenjc What do you think?

**Comment by jichenjc** [comment]
yeah, I agree it will be easier to check only one PR and do local try as well..thanks

**Pull request closed without merging**
