### PR TITLE
Add chaosaffe to cluster-api-openstack-maintainers

### PR DESCRIPTION
**Pull request by chaosaffe**
**What this PR does / why we need it**:
Adds @chaosaffe (me) as a mainainer for `cluster-api-provider-openstack`
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None
**Special notes for your reviewer**:
This will give @chaosaffe (me) rights to approve and merge PR's in this repository

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
/lgtm
Thanks for joining this org. : )

**Comment by m1093782566** [comment]
Welcome!

**Pull request merged**
