### PR TITLE
:bug: [v0.5.0] Prevent creation of floating IPs when reconcile load balancer in non ACTIVE state

### LINKED ISSUE #1114: Load balancer in state different from ACTIVE could cause the creation of many floating ip's
/kind bug

I would like to prevent the creation of unused floating ip's during load balancer reconcilation to avoid waste of resources. This happens, when a load balancer exists but it's state differs from 'ACTIVE'.

Actual behavior

- during reconcilation the controller waits for the load balancer to get ACTIVE
in case of timeout the load balancers the state of the load balancer is ignored and the error is hidden by a general timeout error ([loadbalancer.go#waitForLoadBalancerActive](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/d407435ee95672f3480a7912ee22f66895b64daa/pkg/cloud/services/loadbalancer/loadbalancer.go#L528))

- if an existing load balancer is reconciled and this loadbalancer is in a state other than' 'ACTIVE', following network recources will be created, even if this loadbalancer is in state ERROR
    - [getOrCreateLoadbalancer](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/d407435ee95672f3480a7912ee22f66895b64daa/pkg/cloud/services/loadbalancer/loadbalancer.go#L55) with existing load balancer in state 'ERROR'
    - [checkIfLbExists](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/d407435ee95672f3480a7912ee22f66895b64daa/pkg/cloud/services/loadbalancer/loadbalancer.go#L440) finds the load balancer with that state 'ERROR'
    - which has no IPAddress, so a new one will be requested until the quota exeeds
([from here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/d407435ee95672f3480a7912ee22f66895b64daa/pkg/cloud/services/loadbalancer/loadbalancer.go#L61))

Expected behavior

- an error during load balancer creation should prevent further tries to reconcile, 
any other state than ACTIVE should lead to an error

<sub>Michael Grote <michael.grote@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>

### PR DESCRIPTION
**Pull request by tfussell**
**What this PR does / why we need it**:

I have been running into this issue (#1114 #1159) often recently. It is annoying to have to clean up the extra floating IPs manually. The fix on `main` hasn't been released yet so I would like to backport it for release as v0.5.3.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1114
Cherry-pick of #1115

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
I would personally be ok with another 0.5.x bump containing this cherry-pick.

**Comment by jichenjc** [comment]
I am +1 to release 0.5.3

**Comment by tfussell** [comment]
I'm not sure what the failure about `cert-manager` has to do with this change. Is this a normal flaky test?

**Pull request merged**
