### PR TITLE
🌱 CI: Increase IOPS for the devstack disks

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

This is an attempt to see if disk performance is what makes our CI unstable.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by lentzi90** [comment]
So far so good with larger disk. The larger the disk, the better the performance.
- Devstack success 1
- Devstack failure 0

**Comment by lentzi90** [comment]
Rerunning a few times to get some statistics...
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
Devstack success 2
Devstack failure 0
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
Devstack success 2
Devstack failure 1 :disappointed: 
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by EmilienM** [comment]
/lgtm
feel free to approve when you feel it's ready

**Comment by EmilienM** [comment]
let's consider https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2319 as well

**Comment by lentzi90** [comment]
Devstack success 3
Devstack failure 1
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
Devstack success 4
Devstack failure 1
/test pull-cluster-api-provider-openstack-e2e-test

**Comment by lentzi90** [comment]
6 to 1 is better than what we seen in the periodics. I think the best there has been 4 successful in a row.
/hold cancel
/approve

**Pull request merged**
