### PR TITLE
🐛 Allow UDP traffic over nodeports

### LINKED ISSUE #1395: Nodeports only allows TCP traffic by default
/kind bug

**What steps did you take and what happened:**
I have noticed the by default only TCP traffic is allowed on nodesports.
There is quite a few workloads using UDP (just to bring up one example video conference/meetings) that won't work

The reason for this seems to be `GetSGWorkerNodePort`  (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/securitygroups_rules.go#L225) only returning ONE rule for TCP.

**What did you expect to happen:**
I would expect UDP traffic to be allowed by default.

**Anything else you would like to add:**
I'm working on a PR

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.6.4 (However this is still the case in master)
- Cluster-API version: v1.2.6
- OpenStack version: Train
- Minikube/KIND version: N/A
- Kubernetes version (use `kubectl version`): 1.25.4
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by bl0m1**
**What this PR does / why we need it**:
This PR adds a security group rule to allow UDP over nodeports.

Currently CAPO only allows TCP traffic to pass.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1395

**Special notes for your reviewer**:
N/A

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Review by mnaser — APPROVED** [review]

**Comment by jichenjc** [comment]
looks like the CI error is not related, 

the change looks good
/lgtm

**Pull request merged**
