### PR TITLE
Update Gophercloud to 1.7.0

### PR DESCRIPTION
**Pull request by EmilienM**
Update Gophercloud to the latest stable tag which was released today.
This will fix a few bugs and also add more capabilities that'll needed soon.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by mdbooth — COMMENTED** [review]
/lgtm
/approve

**Comment by mdbooth** [comment]
That test failure was a timeout. We should investigate fully if it happens again.

/retest-required

**Pull request merged**
