### PR TITLE
Follow new way of cluster pause handling

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

sync this paused function with AWS provider (cluster-api currnet way)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
recheck

**Comment by hidekazuna** [comment]
Is this for #731 ?

**Comment by jichenjc** [comment]
no, I only want to replicate newest stuffs from AWS provider during analysis 731
no clue yet how to fix 731

**Comment by jichenjc** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
recheck

**Comment by jichenjc** [comment]
@hidekazuna can you help to take a look at this?thanks~

**Comment by hidekazuna** [comment]
@jichenjc Should we take the following code into account?

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awscluster_controller.go#L265-L336

**Comment by jichenjc** [comment]
@hidekazuna it said `// for AWSCluster resources only` so I didn't copy them .. need more check

**Review by sbueringer — APPROVED** [review]

**Comment by sbueringer** [comment]
> @hidekazuna it said `// for AWSCluster resources only` so I didn't copy them .. need more check

I think it also makes sense for us. Looks like they don't want to reconcile on status updates. I think it's the same for us, but if we're not sure, maybe you can ask in Slack.

**Comment by hidekazuna** [comment]
> > @hidekazuna it said `// for AWSCluster resources only` so I didn't copy them .. need more check
> 
> I think it also makes sense for us. Looks like they don't want to reconcile on status updates. I think it's the same for us, but if we're not sure, maybe you can ask in Slack.

So we need to add for OpenStackCluster resource as they did for AWSCluster, right?

**Comment by sbueringer** [comment]
> > > @hidekazuna it said `// for AWSCluster resources only` so I didn't copy them .. need more check
> > 
> > 
> > I think it also makes sense for us. Looks like they don't want to reconcile on status updates. I think it's the same for us, but if we're not sure, maybe you can ask in Slack.
> 
> So we need to add for OpenStackCluster resource as they did for AWSCluster, right?

I think we have to do this for OpenStackCluster and OpenStackMachine. i think the idea is that a reconcile which updates the status shouldn't trigger another reconcile.

xref:
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awscluster_controller.go#L270
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller.go#L224

**Comment by jichenjc** [comment]
@hidekazuna FYI holiday season coming so might takes me 2 weeks to update this PR again :) 
I will check your and @sbueringer 's comments after that ~

**Comment by hidekazuna** [comment]
@jichenjc @sbueringer I will try to update this PR.

**Comment by hidekazuna** [comment]
#736 is successor.

**Pull request closed without merging**
