### PR TITLE
🐛 Update calico manifest for e2e testing

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

This PR may fix the periodic conformance tests

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts/1550312818316677120

/test pull-cluster-api-provider-openstack-conformance-test

**Special notes for your reviewer**:

Update the calico.yaml via

```
curl -L https://docs.projectcalico.org/v3.23/manifests/calico.yaml > test/e2e/data/cni/calico.yaml
sed -i 's/docker[.]io/quay.io/g' test/e2e/data/cni/calico.yaml
```

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Review by seanschneeweiss — COMMENTED** [review]
:+1:
/lgtm

**Comment by tobiasgiese** [comment]
/hold cancel

Let‘s see if the conformance tests are fixed with this

**Pull request merged**
