### PR TITLE
📖 Fix Link for external openstack template

### PR DESCRIPTION
**Pull request by elafontaine**
The link goes one folder up too much causing the reference link to be broken.

**What this PR does / why we need it**:
The link goes one folder up too much causing the reference link to be broken.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes. 
No, this changes only the documentation.

### CODE REVIEW

**Comment by elafontaine** [comment]
How do I retrigger the CLA ?

**Comment by elafontaine** [comment]
@k8s-ci-robot /check-cla

**Comment by jichenjc** [comment]
@elafontaine have you signed CLA ? or keep recheck doesn't help
@hidekazuna I forgot the link of sign of CLA, do you still remember that?

**Comment by hidekazuna** [comment]
@elafontaine Please check out https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by elafontaine** [comment]
So @hidekazuna , I did register to the CLA, with my gmail account, but for some reason... the robot doesn't see it...

I don't know what I'm missing... the User name isn't looked at, right ?

**Comment by elafontaine** [comment]
My bad, I was blind...

**Comment by jichenjc** [comment]
@elafontaine this is because CI issue , I opened bug https://github.com/theopenlab/openlab/issues/581 and folks are working on it now ...

**Comment by elafontaine** [comment]
Thanks :)

**Comment by elafontaine** [comment]
Will I have to do the merge @hidekazuna ?

Or are you able to follow through from here ?

I'm trying to know what I can do to help move forward, but I can't see anything at the moment.

**Comment by jichenjc** [comment]
@elafontaine thanks for the PR :) it's merged now

**Comment by elafontaine** [comment]
Confirmed issue resolved :) thanks folks :)

**Pull request merged**
