### PR TITLE
Use NewDeploymentClient() to get DeploymentClient

### PR DESCRIPTION
**Pull request by chaosaffe**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
Hi, I think those two ways are actually the same, have any reason about why we have to change it?

**Comment by chaosaffe** [comment]
It is a move towards being able to pass the path in.

It was an inconsistentcy I caught while working on adding support for
user-defined SSH key paths.

**Comment by Lion-Wei** [comment]
@chaosaffe Make sense, thanks. 

But wait for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/36 merge in first, ok?

**Comment by krzyzacy** [comment]
/test all
(check CI)

**Comment by chaosaffe** [comment]
> But wait for #36 merge in first, ok?
SGTM

/hold

**Comment by flaper87** [comment]
(I know it's on hold but)

/lgtm

**Pull request merged**
