### PR TITLE
Adding flaper87 as a cluster-api-openstack-maintainer

### PR DESCRIPTION
**Pull request by flaper87**
Raising my hand to help with reviews and discussions on the cluster-api-provider-openstack. I'm currently focused on testing, developing, and stabilizing this project. I'd like to help with reviews and maintenance as well.

### CODE REVIEW

**Comment by dims** [comment]
cc @Lion-Wei @m1093782566

**Comment by chaosaffe** [comment]
@flaper87 it looks like you aren't yet an org member for @kubernetes-sigs. Can you please request sig membership by opening an issue in http://github.com/kubernetes/org/

**Comment by flaper87** [comment]
oh, mmh, that's embarrasing. I thought I was part of it already: https://github.com/kubernetes/org/pull/144

**Comment by chaosaffe** [comment]
@flaper87 Welcome to the org 😊 

/lgtm

**Comment by Lion-Wei** [comment]
@flaper87 Welcome to the org :smiley:

**Pull request merged**
