### PR TITLE
📖 Add netlify.toml to publish our book

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #783 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by jichenjc** [comment]
@tobiasgiese in case we can create doc automatically, can we add link to README later on? Thanks

**Comment by tobiasgiese** [comment]
> @tobiasgiese in case we can create doc automatically, can we add link to README later on? Thanks

Sure, good point :)
Will do that in a follow-up PR, after the Book is published and the domain accessible.

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Pull request merged**
