### PR TITLE
Add tip for docker limit

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by hidekazuna** [comment]
This is not cluster-api-provider-openstack specific. I think propose to Cluster API is more valuable.

**Comment by jichenjc** [comment]
um.. I understand, but if we can provide some info here , we avoid people to jumping around ..

**Comment by sbueringer** [comment]
@jichenjc @hidekazuna I'm not sure if we should add it or not. On the one hand it's useful if somebody is hitting it on the other hand it's really pretty general advice which is independent of CAPI. I lean into the direction of not adding it as we should not start giving general troubleshooting advice (also this is all documentation we have to maintain and keep up-to-date)

**Comment by jichenjc** [comment]
give another thought, I think we should not add it , it should be general stuff for k8s ecosystem

**Pull request closed without merging**
